<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>popup_Redirect Message</name>
   <tag></tag>
   <elementGuidId>5a2a5d7f-720c-440b-96bd-745537c66e2f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#p0BQe</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='p0BQe']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Redirect Message Pastikan Lokasi Service Ahass Induk Sudah Sesuai. YaTidak' or . = 'Redirect Message Pastikan Lokasi Service Ahass Induk Sudah Sesuai. YaTidak')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Redirect Message Pastikan Lokasi Service Ahass Induk Sudah Sesuai. YaTidak&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e16e8cbe-6c47-4369-86e2-e105086a2485</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>p0BQe</value>
      <webElementGuid>f44002d3-65ac-4073-b0d6-89e9ffa4f4ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-messagebox-window  z-window z-window-highlighted z-window-shadow</value>
      <webElementGuid>82834a63-1889-440f-9a48-24db9cf06723</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Redirect Message Pastikan Lokasi Service Ahass Induk Sudah Sesuai. YaTidak</value>
      <webElementGuid>5225903b-16bd-4902-a8de-259328eef067</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;p0BQe&quot;)</value>
      <webElementGuid>1d5270f2-f06e-40c7-af1c-72e381f8391f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='p0BQe']</value>
      <webElementGuid>f847172a-ca6c-48a9-9e0a-5845c3a65d77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[1]/following::div[2]</value>
      <webElementGuid>d664bbe2-74a8-40dd-8a90-f1003391a7c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]</value>
      <webElementGuid>10fbf192-a614-48e4-b67a-7716e172b461</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'p0BQe' and (text() = 'Redirect Message Pastikan Lokasi Service Ahass Induk Sudah Sesuai. YaTidak' or . = 'Redirect Message Pastikan Lokasi Service Ahass Induk Sudah Sesuai. YaTidak')]</value>
      <webElementGuid>68b0cc07-bb45-4a83-9a0a-e73f94b6e1f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
