<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Print Faktur</name>
   <tag></tag>
   <elementGuidId>79bbf357-1f09-4910-bec2-81ba69a606f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dLuPbo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[1]/div[2]/div[1]/div[3]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[3]/div[1]/div[1]/div[1]/div[3]/table[1]/tbody[1]/tr[1]/td[15]/div[1]/div[1]/div[4]/button[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;WO-X6979-24-12-00002 Non KPB TIDAK TIDAK Ahass Induk B 0002 DWI Multiple Service REGULER 12:33 SO-X6979-24-12-00012 Complete 09-Dec-2024 USER DAW 001 Print Workorder Print Faktur&quot;i] >> internal:attr=[title=&quot;Print Faktur&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0ba71712-dba0-4116-be93-46606492a767</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9f3f82f8-372d-41a2-8348-7ee3c37252cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dLuPbo</value>
      <webElementGuid>4c515886-b0fb-4212-bba9-8b7c93ee478f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-button</value>
      <webElementGuid>ac65b463-a47d-45ae-9e37-197562655a9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Print Faktur</value>
      <webElementGuid>7ecbf0c3-fecc-4e49-a8a3-c3f7b17bdbe6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dLuPbo&quot;)</value>
      <webElementGuid>35747785-e869-45c9-b446-25db09e0dded</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='dLuPbo']</value>
      <webElementGuid>1aa66d21-3a81-42e2-a64c-d0df98f38cb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dLuPbo-chdex']/button</value>
      <webElementGuid>dbcbe123-f686-4eb4-8589-1ff399f1e277</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='USER DAW 001'])[1]/following::button[4]</value>
      <webElementGuid>bdca1c05-4446-4ee0-a768-dc6648a5ae6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Complete'])[1]/following::button[4]</value>
      <webElementGuid>5bb3667d-693c-41ee-879d-4100221b0565</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VST-X6979-24-12-00009'])[1]/preceding::button[2]</value>
      <webElementGuid>623652c9-9fca-4c06-94ff-98bb36eda750</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Non KPB'])[2]/preceding::button[2]</value>
      <webElementGuid>917cce92-b947-4583-99f4-9ca9c4384218</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/button</value>
      <webElementGuid>b0e67475-7d9a-434f-8765-9cb441271bf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'dLuPbo' and @title = 'Print Faktur']</value>
      <webElementGuid>3585b26a-2db1-4bf3-98a7-96fd8fc96e79</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
