<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Print WO</name>
   <tag></tag>
   <elementGuidId>63c278eb-b63c-4db9-a4f0-2a8f2619bea7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dLuP9o</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[1]/div[2]/div[1]/div[3]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[3]/div[1]/div[1]/div[1]/div[3]/table[1]/tbody[1]/tr[1]/td[15]/div[1]/div[1]/div[2]/button[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;WO-X6979-24-12-00002 Non KPB TIDAK TIDAK Ahass Induk B 0002 DWI Multiple Service REGULER 12:33 SO-X6979-24-12-00012 Complete 09-Dec-2024 USER DAW 001 Print Workorder Print Faktur&quot;i] >> internal:attr=[title=&quot;Print Workorder&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8a04c7c5-06a0-4470-9035-3e88142a68df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>74a5346b-1c03-4252-a256-b9455771a7b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dLuP9o</value>
      <webElementGuid>76f90286-cba5-41b2-bcc8-0a0a934003b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-button</value>
      <webElementGuid>5d5afd5a-3bce-4653-9ffe-2611f2d36fb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Print Workorder</value>
      <webElementGuid>0f10727f-9283-490b-98d3-823eedb0ba87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>disabled</name>
      <type>Main</type>
      <value>disabled</value>
      <webElementGuid>cf7bc59b-37ce-4b0c-bf34-7036adf97ac5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dLuP9o&quot;)</value>
      <webElementGuid>4d9bebc4-cff4-40a4-a3dd-b65a275f0e20</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='dLuP9o']</value>
      <webElementGuid>7c2695da-77c6-4c7a-8ab0-a84c0039bb08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dLuP9o-chdex']/button</value>
      <webElementGuid>6d2463c1-172a-4cb4-8e27-ee3e45457564</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='USER DAW 001'])[1]/following::button[2]</value>
      <webElementGuid>af3effaa-8326-44bc-abb3-5dac27eb1f9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Complete'])[1]/following::button[2]</value>
      <webElementGuid>cef12e8e-803c-476d-a4e0-93f5a83488e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VST-X6979-24-12-00009'])[1]/preceding::button[4]</value>
      <webElementGuid>1d871019-642a-4225-976c-d097f53580bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Non KPB'])[2]/preceding::button[4]</value>
      <webElementGuid>282a2400-66ca-468e-978c-e08653cd720c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>fe76a90c-2c63-4163-b9e2-d3d1fbf8444d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'dLuP9o' and @title = 'Print Workorder']</value>
      <webElementGuid>bcc974ca-0404-4fd1-8d45-d455c85884ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
