<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Close Cetak WO</name>
   <tag></tag>
   <elementGuidId>fe0f2c1f-2381-4ae7-83e5-7a4add658f17</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dLuPt41</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[1]/div[6]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/button[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;X&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d97fa58b-ef36-4f4d-9d25-61715ea942e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>513cbc61-38a8-4d93-9632-bb895341803b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dLuPt41</value>
      <webElementGuid>02ec7179-86cc-4074-a29b-8a188ee573eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-close</value>
      <webElementGuid>7fb6e5b0-ca9b-4fa9-8e37-77968abd2b90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>X</value>
      <webElementGuid>324e93e5-77be-459f-90bb-6be2e6d5356e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dLuPt41&quot;)</value>
      <webElementGuid>b0936958-2dbc-4f88-af65-62a575163b92</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='dLuPt41']</value>
      <webElementGuid>a77831e9-ecd1-4794-943d-31e2e3c82f88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dLuPu41']/button</value>
      <webElementGuid>d018cff6-bf29-44bc-8661-46b9ce5fe09b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ukuran Cetakan Work Order'])[1]/following::button[1]</value>
      <webElementGuid>5d8961d3-0b23-4e5c-87a3-74a4faef0c34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CETAK'])[1]/preceding::button[1]</value>
      <webElementGuid>6b91e89d-cb27-44c2-af01-ccdfec50cca5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='X']/parent::*</value>
      <webElementGuid>fc3c9dee-5f86-4404-980f-3d606d565d66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/button</value>
      <webElementGuid>1af4600a-bdf2-4e7b-ac48-090aaea3e292</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'dLuPt41' and (text() = 'X' or . = 'X')]</value>
      <webElementGuid>a19cbb42-5b68-4de6-bedf-46934e4f897d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
