<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Ukuran Kertas</name>
   <tag></tag>
   <elementGuidId>00dab0a8-d86b-4c82-a0a6-faa3fc9c404d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#eLeX4m</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[1]/div[6]/div[1]/div[2]/div[1]/div[1]/select[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;eLeX4m&quot;)[count(. | //*[(text() = 'A4A5' or . = 'A4A5')]) = count(//*[(text() = 'A4A5' or . = 'A4A5')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#eLeXul-cave >> internal:role=combobox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>533deb28-2695-42a9-9999-6f016e30dc76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>eLeX4m</value>
      <webElementGuid>39b005c8-1b96-444e-8562-423218a855b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>a6e84446-cb50-4f2b-ba79-24fbe5bd65a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>A4A5</value>
      <webElementGuid>c12beb16-a1b8-4e51-a173-8a4ddfdd378b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//body[1]/div[6]/div[1]/div[2]/div[1]/div[1]/select[1]</value>
      <webElementGuid>1393245b-91ee-4138-8055-19be8e839a5c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='eLeX4m']</value>
      <webElementGuid>2f774d76-a146-4e66-91df-772c26ad9ee6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='eLeX5m']/select</value>
      <webElementGuid>86cd87e9-e292-46f0-aee0-504695383592</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='X'])[1]/following::select[1]</value>
      <webElementGuid>68bac09e-3e95-4c1e-83da-ccd31b732fcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ukuran Cetakan Work Order'])[1]/following::select[1]</value>
      <webElementGuid>fb31b548-8824-4dae-a733-b67b7005da90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CETAK'])[1]/preceding::select[1]</value>
      <webElementGuid>59d16a40-32f0-4d3c-b5ec-0da09b8cb9c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/select</value>
      <webElementGuid>7455d374-49d1-4400-ab08-2aca2f74584e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'eLeX4m' and (text() = 'A4A5' or . = 'A4A5')]</value>
      <webElementGuid>e4717b57-402b-4f5a-b25c-2d321037edac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
