<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Nama Mekanik</name>
   <tag></tag>
   <elementGuidId>dbe44af5-3067-4c39-966d-e9f3b78e8943</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#m7RB800</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[1]/div[2]/div[1]/div[3]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[4]/div[1]/div[1]/div[1]/div[1]/div[5]/div[1]/div[1]/div[3]/select[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'm7RB800' and (text() = 'DEDE YOKS' or . = 'DEDE YOKS')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#m7RB800</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>9416f8ad-c09f-48e5-b37d-4d737a1df205</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>m7RB800</value>
      <webElementGuid>82663f30-469e-4e1b-bda3-e7e16dd96a09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>adb6f96a-8339-4806-a6a7-e8315d37ebae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>disabled</name>
      <type>Main</type>
      <value>disabled</value>
      <webElementGuid>749d0041-2012-45e9-811e-5f7846152c1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>selectedindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>3d9c95d9-dd6f-4ea8-af91-8927e6957f00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DEDE YOKS</value>
      <webElementGuid>43a11631-8ed0-4709-95a1-1bffcac68739</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;m7RB800&quot;)</value>
      <webElementGuid>2924bdd1-f234-475a-9a3d-852da13638d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='m7RB800']</value>
      <webElementGuid>d7b7b2f1-1cb8-4ed4-8f20-444b8e9b1534</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='m7RB600']/select</value>
      <webElementGuid>24691ef2-ef8c-4a34-b3fa-0b17c232e8b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Nama Mekanik'])[1]/following::select[1]</value>
      <webElementGuid>9649a226-be72-4f1b-938b-c45efb1044cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Tipe KPB'])[1]/following::select[2]</value>
      <webElementGuid>3b2250c0-67fa-42f2-b704-539e93046700</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No. Pit Service'])[1]/preceding::select[1]</value>
      <webElementGuid>664070c6-4212-41fd-b93f-6ef48ca4b643</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipe Pit'])[1]/preceding::select[1]</value>
      <webElementGuid>6f94a0bf-be34-409a-a14a-046c3aebc105</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/select</value>
      <webElementGuid>514dcbe0-319e-4a16-a4a6-3799f1788ecd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'm7RB800' and (text() = 'DEDE YOKSSIDIK YOKSBACHTIAR YORKGENTA YORKBUDI YORKBUDI YORKSYAMSUL YORKBUDI YORKSIDIK YOKSBACHTIAR YORK' or . = 'DEDE YOKSSIDIK YOKSBACHTIAR YORKGENTA YORKBUDI YORKBUDI YORKSYAMSUL YORKBUDI YORKSIDIK YOKSBACHTIAR YORK')]</value>
      <webElementGuid>6a95203e-2984-4a48-bc19-27ad1973e790</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
