<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Tambah Unit</name>
   <tag></tag>
   <elementGuidId>d26790ed-8766-41fe-b073-be32f273ec82</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[1]/div[6]/div[1]/div[5]/div[1]/div[1]/div[1]/div[3]/table[1]/tbody[1]/tr[1]/td[5]/div[1]/button[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#f8TUse1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;1 UTPX99 CBR650F CBR650FAE 2ED M/T&quot;i] >> internal:role=button</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ad0aa6cf-ec9d-44c4-b1b3-f9a6028e503e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>20b70fd0-1c7f-4127-bbbe-9a50c4e738f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>f8TUse1</value>
      <webElementGuid>269861bb-b512-400b-9319-8cfab077d28a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-button</value>
      <webElementGuid>cb782233-a293-4711-ac62-cd7717e03826</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;f8TUse1&quot;)</value>
      <webElementGuid>0c8f89c3-b70a-4fcc-8cf8-666ceb1e4c9e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='f8TUse1']</value>
      <webElementGuid>57136a3e-2f30-405f-9c94-cc898e255310</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='f8TUse1-cell']/button</value>
      <webElementGuid>9a62032d-7064-42d8-8bf3-494a38ae583d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CBR650FAE 2ED M/T'])[1]/following::button[1]</value>
      <webElementGuid>83d580fd-2bf2-4ee2-aa18-dc7b5aba5d66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CBR650F'])[1]/following::button[1]</value>
      <webElementGuid>c5147ea3-6aca-403f-8ee7-6bb253e1581a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UTPX98'])[1]/preceding::button[1]</value>
      <webElementGuid>bd86e65f-8da0-4370-9818-22c1ced1bd66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CBR650F'])[2]/preceding::button[1]</value>
      <webElementGuid>2ca5823a-c458-4947-8cac-965534ef7bb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/div/button</value>
      <webElementGuid>cfe345f9-b09d-47d3-b2ea-cc44ba6dfc6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'f8TUse1']</value>
      <webElementGuid>bba4bdfa-93d6-405d-b572-d0e3491a62f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
