<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Cari Tipe Motor</name>
   <tag></tag>
   <elementGuidId>47afd2f3-58df-4783-b02c-60a9f2ed9031</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[1]/div[6]/div[1]/div[4]/div[1]/div[1]/div[3]/div[1]/button[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#f8TU3x</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#f8TUwy-chdex >> internal:role=button[name=&quot;Cari&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e92176bb-1eb7-4e87-a893-81f5f8d6d488</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4ee97105-b3f1-410a-8b67-bedaeb0daf62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>f8TU3x</value>
      <webElementGuid>7933d884-bdf2-449a-a298-c894082e1854</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-xs z-button</value>
      <webElementGuid>bed762dd-8bd1-4385-97bd-fbba2ca8802b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                        Cari
                                    </value>
      <webElementGuid>4899b94b-ffeb-4b7e-b346-70c0ec51458a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;f8TU3x&quot;)</value>
      <webElementGuid>40e73972-f674-4e68-b31d-7d5a9b0fb1dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='f8TU3x']</value>
      <webElementGuid>0d5f42dc-5579-4dd1-90fc-50b29d3e0def</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='f8TUwy']/button</value>
      <webElementGuid>609b7954-7de7-489c-8559-a5a9ba28d5d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama Unit'])[1]/following::button[1]</value>
      <webElementGuid>6a1cd237-9fc8-47a0-b293-f12066e7f214</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='X'])[2]/following::button[1]</value>
      <webElementGuid>5768dff3-6088-4bc4-b4d3-2ccaffe13cae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No.'])[1]/preceding::button[1]</value>
      <webElementGuid>b4602aba-88ab-464f-90df-644fc55eca04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kode Tipe Unit'])[1]/preceding::button[1]</value>
      <webElementGuid>82596ab5-dec9-4133-821f-1369cfae99f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/button</value>
      <webElementGuid>d14ec00d-5318-4ce6-b9cb-c9ad2d1cc7a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'f8TU3x' and (text() = '
                                        Cari
                                    ' or . = '
                                        Cari
                                    ')]</value>
      <webElementGuid>3961bb13-34b5-4184-8df7-48d05f5c0392</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
