<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_SIMPAN</name>
   <tag></tag>
   <elementGuidId>c3031f2c-937e-4249-8566-61c5f9b69757</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[1]/div[4]/div[1]/div[5]/div[1]/div[1]/div[1]/div[1]/button[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#f8TUzw</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;SIMPAN&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>113fc1c7-40f4-4560-bb98-babf2a89e01d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b32e641f-7e66-4b96-8b11-6231748484dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>f8TUzw</value>
      <webElementGuid>994a36a9-cb20-4657-a395-df5fb319815d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>c9376f7b-b07a-4c7c-ba48-9262a78718bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                SIMPAN
                            </value>
      <webElementGuid>a5da04f1-9ce9-4ce2-b232-876b3b8e266f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;f8TUzw&quot;)</value>
      <webElementGuid>77938ea3-6957-4ec3-81ab-e1baa5230bf6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='f8TUzw']</value>
      <webElementGuid>ad86e7dc-15df-47a9-89e9-669b0edcc046</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='f8TUyw']/button</value>
      <webElementGuid>c593b00a-0112-46f2-aafe-06d1c07a4642</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[6]/following::button[1]</value>
      <webElementGuid>83f9f8d8-0366-4772-ba34-844ac2f5cfbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nomor Telepon'])[1]/following::button[1]</value>
      <webElementGuid>d5826a7f-9ba5-4b36-ab95-8cb72bacd85f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SIMPAN']/parent::*</value>
      <webElementGuid>a4195319-7b0a-4b20-b7b6-ad5fe17ecc03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/button</value>
      <webElementGuid>61e3984d-aefc-4a4b-8f68-cd7f58a404bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'f8TUzw' and (text() = '
                                SIMPAN
                            ' or . = '
                                SIMPAN
                            ')]</value>
      <webElementGuid>42438170-18a8-48a5-9488-92c42f1d68e3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
