<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>popup_Tambah Data Unit Customer</name>
   <tag></tag>
   <elementGuidId>ae5714ca-75db-451e-827a-ce4255fb68d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[1]/div[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#f8TU4m</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=&quot;Tambah Data Unit Customer Perbarui Data Unit Customer Balik Nama Unit Customer X&quot;i >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0a7bc453-4762-4c6b-83d4-4861bf8276aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>f8TU4m</value>
      <webElementGuid>26a09d3f-86a1-4745-a97a-edcda20718cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-window z-window-noborder z-window-noheader z-window-modal z-window-shadow</value>
      <webElementGuid>eaa509cc-767d-4b72-8de7-1d56bda594c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>    Tambah Data Unit Customer Perbarui Data Unit Customer Balik Nama Unit Customer    X      Nama*     ID Jenis Kelamin  GTPRGTLK  ID Tipe Customer  GCJPREGROGCPMGCKKGCOI  Nomor KTP    Unit Tipe*    Cari   Nomor STNK    No Polisi                Nomor Mesin      Nomor Chasis    Tahun Perakitan     Alamat KTP*     Alamat Terkini*     Alamat e-mail*     Kota    Kecamatan    Kelurahan    Nomor Kode Pos    Agama    Nomor Telepon*        
                                SIMPAN
                               </value>
      <webElementGuid>8e989af0-db25-4286-9e3e-aed3c2743616</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;f8TU4m&quot;)</value>
      <webElementGuid>2c0f70d3-3228-4d1e-9dfd-d7d4189c5ced</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='f8TU4m']</value>
      <webElementGuid>253f45da-2d37-4bad-8b97-5fd01527e5a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[1]/following::div[2]</value>
      <webElementGuid>6f073af0-9627-402e-b227-e384e4746ca4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]</value>
      <webElementGuid>5a891949-c823-434a-81fe-b0e27a1b6d71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'f8TU4m' and (text() = '    Tambah Data Unit Customer Perbarui Data Unit Customer Balik Nama Unit Customer    X      Nama*     ID Jenis Kelamin  GTPRGTLK  ID Tipe Customer  GCJPREGROGCPMGCKKGCOI  Nomor KTP    Unit Tipe*    Cari   Nomor STNK    No Polisi                Nomor Mesin      Nomor Chasis    Tahun Perakitan     Alamat KTP*     Alamat Terkini*     Alamat e-mail*     Kota    Kecamatan    Kelurahan    Nomor Kode Pos    Agama    Nomor Telepon*        
                                SIMPAN
                               ' or . = '    Tambah Data Unit Customer Perbarui Data Unit Customer Balik Nama Unit Customer    X      Nama*     ID Jenis Kelamin  GTPRGTLK  ID Tipe Customer  GCJPREGROGCPMGCKKGCOI  Nomor KTP    Unit Tipe*    Cari   Nomor STNK    No Polisi                Nomor Mesin      Nomor Chasis    Tahun Perakitan     Alamat KTP*     Alamat Terkini*     Alamat e-mail*     Kota    Kecamatan    Kelurahan    Nomor Kode Pos    Agama    Nomor Telepon*        
                                SIMPAN
                               ')]</value>
      <webElementGuid>fafb48b8-f2da-4d11-9fab-5cc816c45a37</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
