<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_ID Tipe Customer</name>
   <tag></tag>
   <elementGuidId>18506f28-b468-4f74-a8da-4b188bd85150</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[1]/div[4]/div[1]/div[4]/div[1]/div[1]/div[3]/div[1]/select[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#f8TUzm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=combobox >> nth=2</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>341aa36e-3049-4dd3-8896-0694c1f71f9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>f8TUzm</value>
      <webElementGuid>e1efe81a-2dc4-4f38-9648-c355c86b51eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>b5696e9c-5c5b-424a-bfa1-34505fa1d385</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>GCJPREGROGCPMGCKKGCOI</value>
      <webElementGuid>84d30dfd-aa1c-4200-b517-d22dc5746f08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;f8TUzm&quot;)</value>
      <webElementGuid>98c218df-337e-4455-9b7c-fcda1fe8e7dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='f8TUzm']</value>
      <webElementGuid>eff8e0b7-f02d-40c6-9d20-b542ed7e86f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='f8TUwm']/select</value>
      <webElementGuid>b84c0cb6-3086-469d-8c34-8f0ff2483f72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ID Tipe Customer'])[2]/following::select[1]</value>
      <webElementGuid>bf62d40f-36cc-4ea0-b333-f8ac4f2c9ce2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ID Jenis Kelamin'])[2]/following::select[2]</value>
      <webElementGuid>1c7e889e-11d3-4060-8ec1-0d6e408a9dfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nomor KTP'])[1]/preceding::select[1]</value>
      <webElementGuid>37d88eda-541a-453f-943e-f2664c8baa24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unit Tipe'])[1]/preceding::select[1]</value>
      <webElementGuid>69e800a8-8438-4bc4-9b3f-bed5dcf694a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/select</value>
      <webElementGuid>d93243db-5eff-4878-b537-ee8c9c6c81b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'f8TUzm' and (text() = 'GCJPREGROGCPMGCKKGCOI' or . = 'GCJPREGROGCPMGCKKGCOI')]</value>
      <webElementGuid>49454556-4bba-4a70-950a-9391da535757</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
