<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Edit</name>
   <tag></tag>
   <elementGuidId>3611b25c-6ff0-4e7b-8f29-3c8bab620d22</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#g57P2o-chdex</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='g57P2o-chdex']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#g57P2o-chdex</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>10bad5a5-8744-4669-abe1-7940c8563626</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>g57P2o-chdex</value>
      <webElementGuid>488ac957-1273-456d-9505-2fcb0115dae7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-hlayout-inner</value>
      <webElementGuid>177ee1bb-26fd-4fc8-9127-5dbed1b9b230</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//body[1]/div[2]/div[1]/div[3]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[4]/div[3]/table[1]/tbody[1]/tr[1]/td[16]/div[1]/div[1]/div[1]/div[1]</value>
      <webElementGuid>342dec5d-a0d7-4da1-b871-8e0f1125e2f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='g57P2o-chdex']</value>
      <webElementGuid>2d323530-38ce-4d32-a62f-c47a6469ea1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='g57P3o']/div</value>
      <webElementGuid>76045a2d-8a23-44f4-8b7d-cdfca63f44d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BOOKED'])[1]/following::div[4]</value>
      <webElementGuid>beaea748-17b4-4a2c-9aa2-41a15d184e8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Check In'])[2]/following::div[5]</value>
      <webElementGuid>835f2d42-3e22-4860-a0ad-2f3891b585f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BS-X6979-00001249'])[1]/preceding::div[6]</value>
      <webElementGuid>a0c1a763-69ed-4d2a-ba09-ed92258dfeb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MARKI VOUCHER'])[1]/preceding::div[7]</value>
      <webElementGuid>12030418-5987-4df6-a0ce-6914049c6916</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[16]/div/div/div/div</value>
      <webElementGuid>08e7bd4e-5a53-4ed6-9948-0b3e3e0cf77f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'g57P2o-chdex']</value>
      <webElementGuid>1dad1964-f5df-4c12-86be-3bafb838a08c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
