<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Buat Data Booking</name>
   <tag></tag>
   <elementGuidId>15f1bab1-746a-4403-b847-67ff11d8b86c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#g57Pww</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='g57Pww']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Buat Data Booking&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c63175b7-4488-4aff-902c-5a7945b0912f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>71eea0fa-bb72-4be3-8005-0888e0646e4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>g57Pww</value>
      <webElementGuid>76aef8a3-9fc5-4c06-b05c-e854e4a09404</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-button</value>
      <webElementGuid>8facd798-e366-484d-b8e3-b8bb2e6d5eaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        Buat Data Booking
                    </value>
      <webElementGuid>5d497199-9e72-4fda-a9f2-dc0b428ce043</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;g57Pww&quot;)</value>
      <webElementGuid>a9623944-4f8a-4eae-a608-9c8d21424a5a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='g57Pww']</value>
      <webElementGuid>e8da98c2-af83-4053-889a-73fae487df37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='g57Pvw']/button</value>
      <webElementGuid>def9c9c8-007f-47ce-8443-340ca128ea65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp.'])[6]/following::button[1]</value>
      <webElementGuid>49e3c71d-f7a6-45f3-82df-4f89d1a24281</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TOTAL SETELAH DISKON'])[2]/following::button[1]</value>
      <webElementGuid>da496a03-3112-426f-a9d8-2aed91fd53fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Buat Data Booking']/parent::*</value>
      <webElementGuid>fbd28a6e-93e3-48d1-b723-d5f8aad9087d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/button</value>
      <webElementGuid>a326f2ea-3aa0-409b-8bc7-e00860288131</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'g57Pww' and (text() = '
                        Buat Data Booking
                    ' or . = '
                        Buat Data Booking
                    ')]</value>
      <webElementGuid>c07d4878-b37e-47b7-b7ea-ad88ed75e614</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
