<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Close Popup Waktu Service</name>
   <tag></tag>
   <elementGuidId>edda6376-4ccf-4af3-a471-0f2333e708b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#g57P4z</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='g57P4z']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#g57Pwy-cave >> internal:role=button[name=&quot;X&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f3e833f2-cb66-4fb4-a81c-8f58eec17563</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f143c7e7-1572-41a2-84d9-49f7522e3748</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>g57P4z</value>
      <webElementGuid>ec6a49fc-3d9e-4f3b-a306-ba246ea35577</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-close</value>
      <webElementGuid>76340d73-2e9c-41aa-97bd-92eaf0d39602</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>X</value>
      <webElementGuid>b848d55b-fc32-4336-bcde-3333e737e80f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//body[1]/div[7]/div[1]/div[2]/div[2]/div[1]/div[1]/button[1]</value>
      <webElementGuid>bdad29be-856c-4ff2-9886-1821e404c771</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='g57P4z']</value>
      <webElementGuid>cfb31baa-1064-4cc1-898c-3ea51623c04b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='g57P3z']/button</value>
      <webElementGuid>4fbfeecc-ab1d-48a4-b0f5-edd2eb0566fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Waktu Service'])[1]/following::button[1]</value>
      <webElementGuid>e6629217-001c-4f9e-ab2c-4358ceed3092</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buat Data Booking'])[1]/following::button[2]</value>
      <webElementGuid>d404bdc1-9de9-461f-bbd7-4e7e0a4d0c5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Waktu Service'])[2]/preceding::button[1]</value>
      <webElementGuid>3e6be644-615a-4436-873e-6c9d854f0c18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/button</value>
      <webElementGuid>3917bea9-1fee-4da0-a73d-18f01c135dc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'g57P4z' and (text() = 'X' or . = 'X')]</value>
      <webElementGuid>02f4bb6c-d98f-4b62-981e-4cd095852b90</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
