<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Delete</name>
   <tag></tag>
   <elementGuidId>edfb50ee-95b4-45a2-9efc-53e26299dad5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#g57P5o-chdex</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='g57P5o-chdex']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#g57P5o-chdex</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>aa1f2359-2109-4ce6-bbaa-de42049c2196</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>g57P5o-chdex</value>
      <webElementGuid>adc16202-4e5a-4494-8bbd-ee9443f8febd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-hlayout-inner</value>
      <webElementGuid>de9e7b6c-aa8d-482b-9aab-a4d1611890a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//body[1]/div[2]/div[1]/div[3]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[4]/div[3]/table[1]/tbody[1]/tr[1]/td[16]/div[1]/div[1]/div[1]/div[2]</value>
      <webElementGuid>ce9b69b9-6e81-4204-9a0c-559dbe0603fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='g57P5o-chdex']</value>
      <webElementGuid>7107a990-8cbb-4cc0-a86a-0a4782aab7be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='g57P3o']/div[2]</value>
      <webElementGuid>de979339-87c0-4ea6-9ae9-86469fbe0398</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BOOKED'])[1]/following::div[5]</value>
      <webElementGuid>58a30aca-10ca-42ac-b5dc-6010f149e29d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Check In'])[2]/following::div[6]</value>
      <webElementGuid>feffbece-63b0-4bc5-a9ba-2ff8c02559b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BS-X6979-00001249'])[1]/preceding::div[5]</value>
      <webElementGuid>7cd21f2c-cbf8-461f-a125-e48429d756dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MARKI VOUCHER'])[1]/preceding::div[6]</value>
      <webElementGuid>9f1e160e-9498-4f5e-8aec-7e57a5b29b5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[16]/div/div/div/div[2]</value>
      <webElementGuid>daf5e056-8edb-4b3b-ab8b-cd836aa48bda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'g57P5o-chdex']</value>
      <webElementGuid>18f05453-97af-487a-8014-3a1898865381</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
