<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tahun Perakitan</name>
   <tag></tag>
   <elementGuidId>31b591a6-ff8a-4190-b649-d48e5e336756</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#uIsPmu</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='uIsPmu']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#uIsPju-chdex >> internal:role=textbox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b286fd4c-a332-4ef1-b50d-62a3417fbffb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uIsPmu</value>
      <webElementGuid>cc01fe8b-a331-4bdd-ad36-435b1223e1c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-textbox</value>
      <webElementGuid>39532b80-05f0-40e0-aaf3-22b199a2838b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>75e20f5e-b676-46f0-8dae-23dada490dfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>db98461c-4bde-4734-9ca5-8a9948c4f53e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uIsPmu&quot;)</value>
      <webElementGuid>e3f4e7a5-6ccb-43bb-98cc-e22bad84af8b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='uIsPmu']</value>
      <webElementGuid>89080c72-f425-4974-a157-428c49636d7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='uIsPlu']/input</value>
      <webElementGuid>00f2a685-222f-46f5-9206-d31ac05527cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/input</value>
      <webElementGuid>64d65d66-1160-4fbc-b96b-2ab995323075</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'uIsPmu' and @type = 'text']</value>
      <webElementGuid>7e2fd4cd-7c6d-4dbf-a892-5394bf1e5f8e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
