<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__NoPolisi1</name>
   <tag></tag>
   <elementGuidId>28b0df92-2308-4689-8d94-278e1500ca84</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#g57Pj00</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[1]/div[4]/div[1]/div[3]/div[3]/div[1]/div[1]/div[3]/div[1]/div[2]/div[1]/input[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#g57Pj00</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d54d6d46-9548-4c63-b134-7cb7ab7f1925</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>g57Pj00</value>
      <webElementGuid>d6ce9b7b-16a5-4da9-b306-cf663ec00a78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>06ed9ea1-49a8-4be9-ad0f-e7b6b444ce36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>73bf788a-0265-495b-91c0-6b505e4a62ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>71002034-8eb7-4ae6-939c-f197d4e65b68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//body[1]/div[4]/div[1]/div[3]/div[3]/div[1]/div[1]/div[3]/div[1]/div[2]/div[1]/input[1]</value>
      <webElementGuid>c294b676-e50a-4d22-9326-b38979e8ab99</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='g57Pj00']</value>
      <webElementGuid>f4dfde77-1236-48f6-b1bf-f45b7a0e69fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='g57Ph00']/input</value>
      <webElementGuid>dc1aaba2-1f7f-4dce-a66a-c860f5884e41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>4306c6d1-f38a-4478-97c1-82d840e0f201</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'g57Pj00' and @type = 'text']</value>
      <webElementGuid>8752d39a-f592-4dc0-8a43-611d7df95007</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
