<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__Tanggal Service</name>
   <tag></tag>
   <elementGuidId>fc64c3fe-2bdf-44a4-abdf-96b6f5f8a4d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#g57P7m-real</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='g57P7m-real']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Pilih Tanggal Service&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>17e51329-87a7-4703-a2fc-fdb3361618a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>g57P7m-real</value>
      <webElementGuid>9f30ed71-9f14-4fb3-b8ac-50b7f1ee5d65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-datebox-input</value>
      <webElementGuid>5d37f07f-51fc-4bbd-bc7f-f00ba23991f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>14238049-85e1-458f-90bb-b9917673dc15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6afb4a19-54e7-456c-9b7c-cd1dd9fef88c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>11</value>
      <webElementGuid>2332f753-8390-4a74-bdcf-c073ef0b055e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Pilih Tanggal Service</value>
      <webElementGuid>25053aba-0658-43ca-9a6e-dee3464a8d40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;g57P7m-real&quot;)</value>
      <webElementGuid>d86b8998-f556-4c17-b29d-da2addcea6c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='g57P7m-real']</value>
      <webElementGuid>88c0a116-fb9b-47c4-86d6-92406e9aba80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='g57P7m']/input</value>
      <webElementGuid>917a1e90-11e6-48c5-a7ac-1e33e7741cb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/span/input</value>
      <webElementGuid>5fe0b90d-52b3-46a2-8ef0-783e18acf474</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'g57P7m-real' and @type = 'text' and @placeholder = 'Pilih Tanggal Service']</value>
      <webElementGuid>d7695c09-8c53-45ee-bf85-8dd254d605b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
