<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Jam Service</name>
   <tag></tag>
   <elementGuidId>c765d2cb-1c22-4725-9ed9-f23d52bc22cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#g57Pn00-cnt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='g57Pn00-cnt']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = '17:00-18:00' or . = '17:00-18:00')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;11:00-12:00&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>62516be5-629c-4fe2-a0b3-0f7353a05a90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>g57Pn00-real</value>
      <webElementGuid>f027567f-0bac-42bb-8bd9-607da6eb6a5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>g57Pn00-cnt</value>
      <webElementGuid>ddca7e67-a870-4c33-8928-8c2acbb0b165</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-radio-content</value>
      <webElementGuid>4283c1a1-47ab-4f2a-9610-714eb120ae56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>17:00-18:00</value>
      <webElementGuid>72d4ba0f-bd55-4723-9320-53e6cfad7403</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;g57Pn00-cnt&quot;)</value>
      <webElementGuid>cba5dfa5-e433-45ca-90fa-c47c777212d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='g57Pn00-cnt']</value>
      <webElementGuid>1627a199-74bb-4573-9bfe-2df7b30f94b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='g57Pn00']/label</value>
      <webElementGuid>af14338c-6076-4f1c-94db-ade057f73c8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='X'])[2]/following::label[11]</value>
      <webElementGuid>a14ee009-2d41-4a05-8172-593a9e70cfdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Waktu Service'])[1]/following::label[11]</value>
      <webElementGuid>c4c95771-a750-4b4e-9739-4372a944951b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Waktu Service'])[2]/preceding::label[13]</value>
      <webElementGuid>999c8b76-1621-4bf4-a603-0c20f0e98f37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='11:00-12:00']/parent::*</value>
      <webElementGuid>5f5448ca-c2e9-4dfa-adcd-0ada15896e34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[11]/label</value>
      <webElementGuid>a4633bdb-5f4c-4672-a6be-1ef0e83aba2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'g57Pn00-cnt' and (text() = '11:00-12:00' or . = '11:00-12:00')]</value>
      <webElementGuid>efab6072-0b66-452a-858f-f257998465b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
