<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Booking Service</name>
   <tag></tag>
   <elementGuidId>78a5451a-b2c0-4c0e-961e-140ecda20285</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#g57Prl</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='g57Prl']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#g57Pgl-cave >> internal:text=&quot;Booking Service&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>111906eb-11db-4b25-a4e8-380c58e0b6f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>g57Prl</value>
      <webElementGuid>c6dff4e4-1bd1-4eb3-bdc8-854aeb746120</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-label</value>
      <webElementGuid>b5f7266c-40a3-4fd3-89b5-1d9276ad7269</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Booking Service</value>
      <webElementGuid>6a18af44-bcc7-42f0-a4f3-b9731e35b14b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//body[1]/div[4]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[1]/span[1]</value>
      <webElementGuid>5404df37-9532-49b9-8624-591d018f5bdf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='g57Prl']</value>
      <webElementGuid>e2843b89-584e-4e5e-83e9-8febe89d6238</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='g57Pnl']/span</value>
      <webElementGuid>d2b67cfa-33f7-4c56-a46c-d0b69dca0a92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[1]/following::span[1]</value>
      <webElementGuid>d2422b6c-166d-4988-9a3b-e4eb87f04161</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='X'])[1]/preceding::span[1]</value>
      <webElementGuid>d11636d0-5cf1-4fda-ae1f-0a4f2fb0e480</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Tanggal Service'])[1]/preceding::span[1]</value>
      <webElementGuid>a78611d8-761d-4b82-a8ab-bb21bb9758c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/span</value>
      <webElementGuid>9ab21a90-1403-456e-bc82-135b6e4b9a72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'g57Prl' and (text() = 'Booking Service' or . = 'Booking Service')]</value>
      <webElementGuid>894dc0c2-2405-4fdb-88ba-4d896bcf7df8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
