<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Monitoring Booking Service</name>
   <tag></tag>
   <elementGuidId>193d18b3-f7ae-469f-b8ec-859c97c09dfb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#g57Pvj</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='g57Pvj']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>p >> internal:has-text=&quot;Monitoring Booking Service&quot;i >> span</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d0f6b6d4-92ef-4010-ad70-e4cf873b5681</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>g57Pvj</value>
      <webElementGuid>439909cd-8abc-4f51-bbe9-a259be5b943f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>166785fb-abb1-49ea-aa9c-ed8269cff285</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Monitoring Booking Service</value>
      <webElementGuid>2d64197c-66e1-4b89-b76a-6aa3e6b7998a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;g57Pvj&quot;)</value>
      <webElementGuid>ef0e5050-e7cd-41e1-a19c-f83f37e246d5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='g57Pvj']</value>
      <webElementGuid>645ee278-8afd-483b-b52d-e69e65d5ffc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p[@id='g57Ptj']/span</value>
      <webElementGuid>e3b9acfe-cc6f-483a-a5d1-057ea0b2c6f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Booking Service'])[2]/following::span[1]</value>
      <webElementGuid>96b7182f-aa49-48a6-9c81-3717e79b30a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pelindungan Data Pribadi'])[2]/following::span[2]</value>
      <webElementGuid>e5ce3fd3-e969-4d11-810e-90b22679988f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tambah'])[1]/preceding::span[1]</value>
      <webElementGuid>dced3eb2-2ec4-4b56-addf-2c199474ee79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih :'])[1]/preceding::span[1]</value>
      <webElementGuid>a5265162-b7e5-4a90-9f91-5d805240b247</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/p/span</value>
      <webElementGuid>5943a378-9d7b-4364-82d6-dd53bcc3c126</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'g57Pvj' and (text() = 'Monitoring Booking Service' or . = 'Monitoring Booking Service')]</value>
      <webElementGuid>fb6b4508-e685-4ea9-9a56-c8c79b1b2544</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
