<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Jam Service</name>
   <tag></tag>
   <elementGuidId>c765d2cb-1c22-4725-9ed9-f23d52bc22cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = '${jamid}' or . = '${jamid}')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#g57Pn00-cnt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='g57Pn00-cnt']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;11:00-12:00&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>2a6de0a4-46df-4362-a67b-cb634587dc88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>g57Pn00-real</value>
      <webElementGuid>b5d444b3-90e3-4a65-8d8b-96eefd53ec2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>g57Pn00-cnt</value>
      <webElementGuid>664b8d8f-379c-4eb2-a76f-927383af6e0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-radio-content</value>
      <webElementGuid>6e985ebc-41d3-4020-b1e0-cdf88f7e7fee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>${jamid}</value>
      <webElementGuid>d209efdc-e07c-4dab-915c-da11e00193dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;g57Pn00-cnt&quot;)</value>
      <webElementGuid>9c7eef6d-1def-4d7a-935f-651a7b673c08</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='g57Pn00-cnt']</value>
      <webElementGuid>3ae47591-4411-4314-8560-311705bc1463</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='g57Pn00']/label</value>
      <webElementGuid>41e0c3e8-bfd5-4d3d-9d45-c6e4845defe9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='X'])[2]/following::label[11]</value>
      <webElementGuid>037390dd-d132-4e61-8575-83fba891600e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Waktu Service'])[1]/following::label[11]</value>
      <webElementGuid>0479d32e-58ac-4034-900b-ab84e2fc6981</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Waktu Service'])[2]/preceding::label[13]</value>
      <webElementGuid>f74affb9-3915-47da-8a1e-57dfddbcfc3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='11:00-12:00']/parent::*</value>
      <webElementGuid>fa41f257-4163-40dd-89f0-8c32bf33606f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[11]/label</value>
      <webElementGuid>d6da3f67-c026-4c0c-8130-238563c9caa0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'g57Pn00-cnt' and (text() = '11:00-12:00' or . = '11:00-12:00')]</value>
      <webElementGuid>94cb1b7c-70a6-4f60-9174-3550830ea8e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
