<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>popup_Data berhasil disimpan</name>
   <tag></tag>
   <elementGuidId>6c689dc5-f93e-4e69-be5c-9bd71a92a473</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#g57Paz</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='g57Paz']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Data berhasil disimpan&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4e55a337-4bcf-4ce1-92a7-ed69bc8e45ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>g57Paz</value>
      <webElementGuid>cbdf483b-1f5c-4742-ade6-d597d0652386</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-label</value>
      <webElementGuid>ea80dfd0-828f-494a-a947-33a86a699f42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Data berhasil disimpan</value>
      <webElementGuid>b595beeb-b6c1-4b35-a1b4-14ffd7b12d23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;g57Paz&quot;)</value>
      <webElementGuid>f7f0ae15-3883-4a47-a502-687406dc317a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='g57Paz']</value>
      <webElementGuid>50ddcd80-3ec5-4285-8401-00bbcfd586f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='g57P9z']/span</value>
      <webElementGuid>5228808e-f2ec-438b-8153-a2e882cad12a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ZK'])[1]/following::span[1]</value>
      <webElementGuid>3ce31887-210c-48be-aabd-4ccdb7b37306</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OK'])[1]/preceding::span[1]</value>
      <webElementGuid>c2a0978f-b678-4cc4-b0a4-cffb9eae55c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Data berhasil disimpan']/parent::*</value>
      <webElementGuid>c22c7dcc-597c-4795-bcf1-64a362b27fcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/table/tbody/tr/td[3]/div/span</value>
      <webElementGuid>e6850edd-feb5-4954-b2a4-4247daf06fb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'g57Paz' and (text() = 'Data berhasil disimpan' or . = 'Data berhasil disimpan')]</value>
      <webElementGuid>31010e7e-6b10-45f3-bd70-00469b9cb703</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
