<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>popup_Ubah Status Booking</name>
   <tag></tag>
   <elementGuidId>42466753-6f0c-4c8c-a185-7018e93a5fff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#n89Pkl</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='n89Pkl']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Ubah Status Booking ?&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>84dea4a5-cec8-4183-abef-94db4a2d9842</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>n89Pkl</value>
      <webElementGuid>f2e92691-a6ee-40a4-bce1-52566da33f5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-label</value>
      <webElementGuid>a0aad036-b5fd-45d0-a5d6-cf69f8459fb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ubah Status Booking ?</value>
      <webElementGuid>229999a0-29c0-4ec1-8a80-85c73781f8da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;n89Pkl&quot;)</value>
      <webElementGuid>e523a63f-c34d-4fb3-a356-eb23e60015e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='n89Pkl']</value>
      <webElementGuid>a774bbbd-0618-4d5b-ba7d-36172088c798</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='n89Phl']/span</value>
      <webElementGuid>40961ffa-e4a5-4559-a0ff-50eeb6d45477</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Question'])[1]/following::span[1]</value>
      <webElementGuid>9dc5db18-1af5-4ccc-aa18-bc0600c93518</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OK'])[1]/preceding::span[1]</value>
      <webElementGuid>0f18c7a6-ab0b-49e8-8602-bc8e228c75f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::span[1]</value>
      <webElementGuid>721436e7-20c5-4d00-8c05-7dbf58701edd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ubah Status Booking ?']/parent::*</value>
      <webElementGuid>e7fdd70c-c031-4f9b-b90b-336e0c3cb24d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/table/tbody/tr/td[3]/div/span</value>
      <webElementGuid>aff8976a-8256-491c-b88a-0c1f722481eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'n89Pkl' and (text() = 'Ubah Status Booking ?' or . = 'Ubah Status Booking ?')]</value>
      <webElementGuid>f54000eb-cf50-45f9-82c2-1437f7668a21</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
