<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>popup_Question</name>
   <tag></tag>
   <elementGuidId>861c46bb-63a7-4ac5-8ad7-63adde032533</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#g57P0x</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='g57P0x']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Apakah anda yakin data input sudah sesuai dan ingin melakukan input Booking Serv&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e341cdd7-ae19-43e5-8ddf-ba8611982577</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>g57P0x</value>
      <webElementGuid>8226d76d-a858-4ea1-809a-16db6e534ee4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-label</value>
      <webElementGuid>33b384cd-e3d1-4c3b-986c-500f60f386d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Apakah anda yakin data input sudah sesuai dan ingin melakukan input Booking Service?</value>
      <webElementGuid>5c4cc2fd-e458-4429-82d4-34a0939f0449</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;g57P0x&quot;)</value>
      <webElementGuid>df135359-d3bc-4ebf-9175-1f2315b15972</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='g57P0x']</value>
      <webElementGuid>ff70f783-4cf2-408b-a47e-3729bfbd0ed9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='g57P6x']/span</value>
      <webElementGuid>2ee288d8-9ec4-4693-a568-0871ab653fbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Question'])[1]/following::span[1]</value>
      <webElementGuid>59b5fefe-c3d4-48c7-b709-bcdc1129adcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buat Data Booking'])[1]/following::span[1]</value>
      <webElementGuid>931082b1-5eef-492a-a08e-4f3104d154bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OK'])[1]/preceding::span[1]</value>
      <webElementGuid>ff08b12b-7624-448d-8014-1b3b5b0f0757</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::span[1]</value>
      <webElementGuid>88dbe2c1-c836-4d6c-aec9-cb0df2d75ea5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Apakah anda yakin data input sudah sesuai dan ingin melakukan input Booking Service?']/parent::*</value>
      <webElementGuid>96d50b09-5a63-4b60-a24e-ee01c92402be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/table/tbody/tr/td[3]/div/span</value>
      <webElementGuid>2d4476ca-116a-4664-9658-076e14513463</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'g57P0x' and (text() = 'Apakah anda yakin data input sudah sesuai dan ingin melakukan input Booking Service?' or . = 'Apakah anda yakin data input sudah sesuai dan ingin melakukan input Booking Service?')]</value>
      <webElementGuid>9d8fdba0-6c80-45a4-8980-5183d3dccff5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
