<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>popup_Konfirmasi Delete</name>
   <tag></tag>
   <elementGuidId>95edf814-7e06-4554-9439-9a05cafc4867</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#g57Pi20</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[1]/div[5]/div[2]/table[1]/tbody[1]/tr[1]/td[1]/table[1]/tbody[1]/tr[1]/td[3]/div[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Apakah anda yakin ingin membatalkan Booking ini?' or . = 'Apakah anda yakin ingin membatalkan Booking ini?')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Apakah anda yakin ingin membatalkan Booking ini?&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ea9b5407-7233-47eb-bd6d-fdfe7e976c41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>g57Pi20</value>
      <webElementGuid>1a7cbaad-ba22-41e0-86cb-115399938bd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-label</value>
      <webElementGuid>82eb61ff-8a3e-40f8-9d13-13e8c828eb63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Apakah anda yakin ingin membatalkan Booking ini?</value>
      <webElementGuid>d460143c-2ac1-4d3b-b4ab-fdcf23a5b3ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;g57Pi20&quot;)</value>
      <webElementGuid>7c5bc981-53a2-4f01-9300-daf53cf0dcd9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='g57Pi20']</value>
      <webElementGuid>ce3c022e-d001-4504-865b-715f6dd77123</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='g57Ph20']/span</value>
      <webElementGuid>d0824f5c-ba86-4bb1-97f6-2eff1f1caa86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ZK'])[1]/following::span[1]</value>
      <webElementGuid>0b582ccc-8430-4b83-b763-c9f6e20fc913</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OK'])[1]/preceding::span[1]</value>
      <webElementGuid>0692f3c4-0c43-4982-bf86-1d42e374ff7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Apakah anda yakin ingin membatalkan Booking ini?']/parent::*</value>
      <webElementGuid>3cde2f55-34b2-410f-8cfe-d6052be7d13b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/table/tbody/tr/td[3]/div/span</value>
      <webElementGuid>166e9230-d2ef-4664-bf91-afb5bc44e97b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'g57Pi20' and (text() = 'Apakah anda yakin ingin membatalkan Booking ini?' or . = 'Apakah anda yakin ingin membatalkan Booking ini?')]</value>
      <webElementGuid>6514eb31-27d8-48c8-b499-3b34b7c27540</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
