<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>popup_Waktu Service</name>
   <tag></tag>
   <elementGuidId>842a23fa-8a43-4ab1-a5bc-7a55c9603632</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#g57Ph_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='g57Ph_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Waktu Service&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>06d3c9b5-ec1c-4a1f-9d84-f9ffd77d04e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>g57Ph_0</value>
      <webElementGuid>f4cec1b0-829a-448b-8ca1-ec6632d467ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-label</value>
      <webElementGuid>9e2f399c-3055-426d-ac6e-ce95a8cd4d4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Waktu Service</value>
      <webElementGuid>4b536266-727d-4bce-87e3-790fb5ae0551</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;g57Ph_0&quot;)</value>
      <webElementGuid>7bcb720d-3e93-454e-a8d2-7e070055d2ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='g57Ph_0']</value>
      <webElementGuid>444b0230-62f3-4d8c-86aa-9e7567e40931</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='g57P_z']/span</value>
      <webElementGuid>3cf6b1b7-ce7d-442b-9432-aedbee1f31e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buat Data Booking'])[1]/following::span[1]</value>
      <webElementGuid>31c5e7c2-3c06-4772-a1ef-44b310cbc293</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp.'])[6]/following::span[2]</value>
      <webElementGuid>02b4ac74-0d2c-4079-aa25-99bd5971581e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='X'])[2]/preceding::span[1]</value>
      <webElementGuid>1b2621aa-f3f2-4e6a-a7a4-257d3c976760</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Waktu Service'])[2]/preceding::span[25]</value>
      <webElementGuid>074f299a-3be9-4d7c-87c6-23cf287a847c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Waktu Service']/parent::*</value>
      <webElementGuid>d5cb8c9a-8306-4fd6-baac-64f50e9e7c78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div[2]/div/div/span</value>
      <webElementGuid>eb4f0402-2628-4a4a-a9b5-e423fd823557</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'g57Ph_0' and (text() = 'Waktu Service' or . = 'Waktu Service')]</value>
      <webElementGuid>65f8c62f-04e0-411f-9e40-1ffc2b2f4ab0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
