<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>popup_Booking Service berhasil dihapus</name>
   <tag></tag>
   <elementGuidId>d7b371f2-b713-426a-ba5a-f5e0ec61fc70</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#g57P6v</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='g57P6v']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//body[1]/div[4]/div[2]/table[1]/tbody[1]/tr[1]/td[1]/table[1]/tbody[1]/tr[1]/td[3]/div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Booking Service BS-X6979-00001251 berhasil dihapus.&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>65322793-63c0-4754-b593-7a75455840ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>g57P6v</value>
      <webElementGuid>3c219dab-e498-4fa2-b2c3-673cd49b1077</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-label</value>
      <webElementGuid>749c0f8d-6844-49de-8f01-a982ccd20005</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Booking Service </value>
      <webElementGuid>baeeb04a-4ebb-41af-9b0a-427954d478c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//body[1]/div[4]/div[2]/table[1]/tbody[1]/tr[1]/td[1]/table[1]/tbody[1]/tr[1]/td[3]/div[1]</value>
      <webElementGuid>e5f2c047-f57d-4ae2-910e-bdf782f10e62</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='g57P6v']</value>
      <webElementGuid>703b3876-9cfa-443e-a725-ad141e6ffbef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='g57P5v']/span</value>
      <webElementGuid>f65230e8-fc9c-4b6e-b0ca-c0a2726e8b5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ZK'])[1]/following::span[1]</value>
      <webElementGuid>3ee0b633-f441-4847-825a-df35ee604490</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OK'])[1]/preceding::span[1]</value>
      <webElementGuid>91152547-f45c-4cbf-9767-8aeca81fa35e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Booking Service BS-X6979-00001251 berhasil dihapus.']/parent::*</value>
      <webElementGuid>6849c4c2-ca7e-4b97-adf9-707ae5596b0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/table/tbody/tr/td[3]/div/span</value>
      <webElementGuid>07358692-6af5-47c4-9baa-c62e8b17fa15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'g57P6v' and (text() = 'Booking Service BS-X6979-00001251 berhasil dihapus.' or . = 'Booking Service BS-X6979-00001251 berhasil dihapus.')]</value>
      <webElementGuid>9f322be1-c8ca-4c72-a145-7f273c07287a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
