<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Move to Regular PIT</name>
   <tag></tag>
   <elementGuidId>788e7005-99e6-474c-8f3e-4d4e26278a4f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='qQAPlf0']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//body[1]/div[4]/div[1]/div[5]/div[1]/div[2]/button[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#qQAPlf0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Move to Regular PIT&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>619323c3-b10b-434c-ae32-8c9cb495e4ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>58453fa5-64dd-4fa2-86ab-22ea23b7cde5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>qQAPlf0</value>
      <webElementGuid>8948f5c6-6f42-4b8e-95c9-9b7063ae0e5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tombol btn btn-primary</value>
      <webElementGuid>afbb278d-fe27-478f-988f-ba1202e08d7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        Move to Regular PIT
                    </value>
      <webElementGuid>f840c94e-0bef-42ae-b52d-44b3116c3a46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//body[1]/div[4]/div[1]/div[5]/div[1]/div[2]/button[1]</value>
      <webElementGuid>5b724467-a445-462d-8d20-c0d34ff83425</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='qQAPlf0']</value>
      <webElementGuid>46b3c159-5958-4933-91fc-8b0493ea2e90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='qQAPkf0']/button</value>
      <webElementGuid>7dc8c19c-abf6-4a49-85d9-21a99a40b7f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move to HR PIT'])[1]/following::button[1]</value>
      <webElementGuid>7935c767-5bbd-4018-ae06-b75697667276</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Work Order Detail'])[1]/following::button[2]</value>
      <webElementGuid>b7347d16-0961-42ce-abc3-558e09b95fa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hold WO'])[1]/preceding::button[1]</value>
      <webElementGuid>1737b132-7c2e-415a-9a38-39231511cab9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Finish'])[1]/preceding::button[2]</value>
      <webElementGuid>8fb59211-ca7b-4154-9700-4095a1b6dc02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Move to Regular PIT']/parent::*</value>
      <webElementGuid>935663b3-46ad-4c47-85f4-0a6c766cfd2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>af7efb33-3f74-4281-8b0d-1f3fb9b0dcd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'qQAPlf0' and (text() = '
                        Move to Regular PIT
                    ' or . = '
                        Move to Regular PIT
                    ')]</value>
      <webElementGuid>0d317628-f1ef-4af9-a9c5-1390e8874d85</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
