<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Move to HR PIT</name>
   <tag></tag>
   <elementGuidId>0077b341-16e6-4e81-a2f2-60313370e080</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='qQAPjf0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#qQAPjf0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Move to HR PIT&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5efa29ed-74c5-435d-82de-4110f3e4ce35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c7354a65-6421-4fa0-9e27-a5b8526e5528</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>qQAPjf0</value>
      <webElementGuid>96de70e7-a6e1-4cc6-9b74-6b22fd9baf29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tombol btn btn-primary</value>
      <webElementGuid>d53a59e7-e343-4a90-ac5d-84a4aef33956</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        Move to HR PIT
                    </value>
      <webElementGuid>0f11347a-7f8a-412a-a419-e3fffab1cedb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;qQAPjf0&quot;)</value>
      <webElementGuid>0cdfc2e6-522a-4742-9aa3-7cce71cfa0f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='qQAPjf0']</value>
      <webElementGuid>c9c349d8-3c31-404b-9a16-748a765c3992</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='qQAPif0']/button</value>
      <webElementGuid>06cce5c3-315c-45f3-91c4-7b16cf08bd5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Work Order Detail'])[1]/following::button[1]</value>
      <webElementGuid>6ff18281-f616-47a8-a9ff-d052eb05d2b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Work Order'])[4]/following::button[2]</value>
      <webElementGuid>fc3cd54f-c02a-489f-b3f8-a2f60ed3132e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move to Regular PIT'])[1]/preceding::button[1]</value>
      <webElementGuid>8d7a6e8c-0b99-4aeb-99a3-32f23dff7218</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hold WO'])[1]/preceding::button[2]</value>
      <webElementGuid>07930e15-b841-489a-9e2d-2c1ab0c2246b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Move to HR PIT']/parent::*</value>
      <webElementGuid>e6ab3cb2-bc37-4d89-be5f-4e775ebda28b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/button</value>
      <webElementGuid>1ca4c620-8e9d-4e73-98b0-58cb938f6064</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'qQAPjf0' and (text() = '
                        Move to HR PIT
                    ' or . = '
                        Move to HR PIT
                    ')]</value>
      <webElementGuid>2319bf2d-11b9-49ff-bd5b-331b1bce737b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
