<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Work Order Detail</name>
   <tag></tag>
   <elementGuidId>6af9ae71-00ce-4ae8-9e6a-55a41fb2b8aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[1]/div[4]/div[1]/div[4]/div[1]/div[4]/div[1]/div[1]/button[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#qQAP8_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Work Order Detail&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ee29d774-3317-471b-bbb7-fedd2f10e6f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f769a7db-b137-468a-ae21-dfcf9f726cb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>qQAP8_0</value>
      <webElementGuid>4951c705-eef5-4c8a-9414-e1eddf2ebb59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tombol btn btn-primary</value>
      <webElementGuid>80aef23d-d7bf-433a-b89c-5994f46db0c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                Work Order Detail 
                            </value>
      <webElementGuid>8415c157-56f3-44f3-8f18-0c57173caf59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;qQAP8_0&quot;)</value>
      <webElementGuid>ca93a309-8cd3-4c51-ad89-436ada9ed746</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='qQAP8_0']</value>
      <webElementGuid>bd3e8233-26d4-4235-ae07-4da60466ea58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='qQAP7_0']/button</value>
      <webElementGuid>19866120-9979-413b-913c-9fa4cf047f36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Work Order'])[4]/following::button[1]</value>
      <webElementGuid>387dded8-390b-403d-bedc-392b31240204</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No Polisi Unit'])[1]/following::button[1]</value>
      <webElementGuid>217a6eb6-beaf-40df-9fa4-85f96eb4664f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move to HR PIT'])[1]/preceding::button[1]</value>
      <webElementGuid>f9c72ed1-de02-4076-b717-6e28ac423203</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move to Regular PIT'])[1]/preceding::button[2]</value>
      <webElementGuid>621b8e93-94b3-4c44-94a0-4253ae163fe6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Work Order Detail']/parent::*</value>
      <webElementGuid>9f46d6ef-457c-4630-add5-9419f17fd672</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/button</value>
      <webElementGuid>4f2f62eb-57db-4ba9-ab6f-1bf89f6a0897</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'qQAP8_0' and (text() = '
                                Work Order Detail 
                            ' or . = '
                                Work Order Detail 
                            ')]</value>
      <webElementGuid>d0721e7e-9277-477d-b6ce-c734e3c7ee9d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
