<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_No Polisi Unit</name>
   <tag></tag>
   <elementGuidId>ddc8e42a-bf98-4c65-bdb8-f834d1d9a077</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='qJFPp00']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//body[1]/div[4]/div[1]/div[4]/div[1]/div[3]/div[1]/div[1]/input[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#qJFPp00</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox >> nth=2</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9bd67e92-0779-4d4e-af6e-4872d11ce844</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>qJFPp00</value>
      <webElementGuid>91655b46-bd7c-4b42-9497-c61fb45095cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-readonly</value>
      <webElementGuid>f1b7d8f7-ee6e-4b8a-addd-fed950965e9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>${nopolisiid}</value>
      <webElementGuid>0588aec2-28d8-4f71-847b-ecbad9635163</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>23ba5b84-4da0-49ea-936f-edcdbc290089</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>3566d13d-ee10-46b3-bf20-a44cc72bbf88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//body[1]/div[4]/div[1]/div[4]/div[1]/div[3]/div[1]/div[1]/input[1]</value>
      <webElementGuid>1610a1f8-b3ae-4bef-9b89-41249ce04a21</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='qJFPp00']</value>
      <webElementGuid>80838233-7896-46a2-99a1-15923709e549</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='qJFPo00']/input</value>
      <webElementGuid>12879162-2cb5-4e44-a2d5-9eb776b5ca44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>2a1fc297-9043-458f-a080-f3553424c38a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'qJFPp00' and @type = 'text']</value>
      <webElementGuid>3e58fdfe-65a3-4b6a-8926-badbd9ce2345</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
