<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Estimasi Biaya</name>
   <tag></tag>
   <elementGuidId>2240eef3-e282-4698-b76d-2ed8aa156b93</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[1]/div[6]/div[1]/div[4]/div[2]/div[1]/div[3]/input[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#r1lTen</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#r1lTen</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>120294dd-52ad-48d7-b6bb-28b699bfc44c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>r1lTen</value>
      <webElementGuid>2d16785a-9c72-4692-9a0f-1915477f98f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-doublebox</value>
      <webElementGuid>100bc53e-95e0-4e0f-82c9-ecfa8862f9c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>29c0f5aa-d2c6-4b69-bd6d-8e1ac7e0409d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>11</value>
      <webElementGuid>0b10e35e-be12-48e9-8246-c6955bc986d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;r1lTen&quot;)</value>
      <webElementGuid>3d7151d2-f6ae-47bd-8f97-54b088164c7d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='r1lTen']</value>
      <webElementGuid>77c30485-91fa-43f9-b02f-1c2596c98bda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='r1lTcn']/input</value>
      <webElementGuid>47529416-dc41-421b-adf5-70ab4c594909</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>95dffd55-02b7-4de2-bda9-82cfd1cbc74c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'r1lTen' and @type = 'text']</value>
      <webElementGuid>ad276a81-5ff5-4430-8aac-c5fe8e7596b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
