<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Nama Mekanik</name>
   <tag></tag>
   <elementGuidId>b769a218-6102-41ac-b167-471e6a4f694b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lVGQ6l</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[1]/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/table[1]/tbody[1]/tr[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = '${mekanikid}' or . = '${mekanikid}')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;PIT 1 DEDE YOKS PIT REGULAR No Polisi : B 0001 AAA&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>06919835-8017-4bea-950e-57ea656039a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-cell</value>
      <webElementGuid>f24694e3-cb8e-498b-8827-c847d7524f3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lVGQ6l</value>
      <webElementGuid>87f5ff3d-b6aa-4aca-ae30-2482d2146764</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>${mekanikid}</value>
      <webElementGuid>68f456e1-768f-4bc7-b63d-1ea8757cb8f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lVGQ6l&quot;)</value>
      <webElementGuid>a25ab199-7d19-4150-83f6-dd25789395a0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='lVGQ6l']</value>
      <webElementGuid>0fcf26aa-569b-4608-8783-e5021e5c2965</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='lVGQ5l']/td</value>
      <webElementGuid>6d8cb92f-549b-42a3-8d69-b8a4bf4f51da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Assignment Service'])[2]/following::td[1]</value>
      <webElementGuid>9d800bef-6f5a-40e3-a699-026c474c3260</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Work Order'])[3]/following::td[1]</value>
      <webElementGuid>47389ac8-3bda-4c89-9c27-a5554ef3e5bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td</value>
      <webElementGuid>a03d7169-3901-440d-bdb2-5b2405e9d49e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'lVGQ6l' and (text() = '  PIT 1  DEDE YOKS  PIT REGULAR  No Polisi :  B 0001 AAA' or . = '  PIT 1  DEDE YOKS  PIT REGULAR  No Polisi :  B 0001 AAA')]</value>
      <webElementGuid>29f643ec-8e86-48de-963b-0ed34461c019</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
