<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Berhasil Hold WO</name>
   <tag></tag>
   <elementGuidId>0f58ceb7-6783-4888-90db-651fd40636f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='r1lTqm']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Berhasil Hold WO' or . = 'Berhasil Hold WO')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#r1lTqm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Alasan Hold WO&quot;i >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9b7b2def-1453-4570-9d8b-95340c730830</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>r1lTqm</value>
      <webElementGuid>1ed006ed-a0a9-4ed4-98e7-fe11d040bbee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-label</value>
      <webElementGuid>fef2ded2-a89f-4cdc-a3af-ca236c7e0dab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Berhasil Hold WO</value>
      <webElementGuid>91b781e1-12c5-4ead-a846-36034a5da33a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;r1lTqm&quot;)</value>
      <webElementGuid>7461b270-bbca-40a9-8470-e89d7b131392</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='r1lTqm']</value>
      <webElementGuid>23aabffb-7be6-4e0d-808b-f3f9f3dfe183</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='r1lTpm']/span</value>
      <webElementGuid>0d388b84-89c0-499c-88b6-f30c6a53bc0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Start'])[1]/following::span[1]</value>
      <webElementGuid>427ef7ca-093d-48b1-bef5-e4a9c30648ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Finish'])[1]/following::span[1]</value>
      <webElementGuid>4b908a7b-6790-4efe-b4fa-f128e1125e8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='X'])[2]/preceding::span[1]</value>
      <webElementGuid>84e92964-e162-4698-8bef-6d5016abf501</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alasan Hold WO'])[2]/preceding::span[1]</value>
      <webElementGuid>463aa61a-6584-43ae-b2ef-2b6bc16515c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Alasan Hold WO']/parent::*</value>
      <webElementGuid>2b89e732-b0bf-4c48-97eb-1ecc05480ca2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/div/div/span</value>
      <webElementGuid>c8e25615-a0ef-4434-8289-81942bcb33cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'r1lTqm' and (text() = 'Alasan Hold WO' or . = 'Alasan Hold WO')]</value>
      <webElementGuid>3f862bec-4c0e-443e-8bf6-f2f2e456e1fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
