<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Alasan Hold Work Order</name>
   <tag></tag>
   <elementGuidId>04a2c159-c403-4461-aa6f-d0f649adfe40</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='r1lTqm']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Alasan Hold WO' or . = 'Alasan Hold WO')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#r1lTqm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Alasan Hold WO&quot;i >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ef1705d9-79fe-4f08-9217-6b698a518417</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>r1lTqm</value>
      <webElementGuid>6837c9e1-4e04-4faf-9a35-fb329acc911b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-label</value>
      <webElementGuid>878d8628-eb06-4f1a-80f3-4d58e7f40985</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Alasan Hold WO</value>
      <webElementGuid>ad3559b5-765a-4e0c-8119-5ebc34417525</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;r1lTqm&quot;)</value>
      <webElementGuid>cf1b3761-d926-4fab-a40f-08a96ac713a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='r1lTqm']</value>
      <webElementGuid>9cd2f2a7-5349-4d41-a26c-924e3d3b5d6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='r1lTpm']/span</value>
      <webElementGuid>0bbf1447-09e2-4a97-87e6-df902c30ae3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Start'])[1]/following::span[1]</value>
      <webElementGuid>5dd3e87a-f3c3-491b-aa61-86aef3f915a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Finish'])[1]/following::span[1]</value>
      <webElementGuid>0e4e8cf3-2df6-49af-ac2e-c610f94f39b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='X'])[2]/preceding::span[1]</value>
      <webElementGuid>fee63b23-4240-468d-949e-037d58442441</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alasan Hold WO'])[2]/preceding::span[1]</value>
      <webElementGuid>aa6ae293-765b-46a0-a78d-f0175b4a5d53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Alasan Hold WO']/parent::*</value>
      <webElementGuid>78bda8cf-8fe9-4b50-b94c-04ff00a0d135</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/div/div/span</value>
      <webElementGuid>0eccb531-1fce-4f28-a04d-383d3e4b2563</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'r1lTqm' and (text() = 'Alasan Hold WO' or . = 'Alasan Hold WO')]</value>
      <webElementGuid>c974e97c-f9b9-4032-b7ab-6035a0e39e87</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
