<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_PDF Viewer</name>
   <tag></tag>
   <elementGuidId>77124c0d-42cb-471d-8937-64b47a597491</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='r1lTjm-cap']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'PDF Viewer' or . = 'PDF Viewer')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#r1lTjm-cap</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;PDF Viewer&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>344eb1bf-7518-472e-a4f5-92304a74499c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>r1lTjm-cap</value>
      <webElementGuid>4c9747cb-e311-405b-826f-20d9ae1c4c51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-window-header z-window-header-move</value>
      <webElementGuid>416b766a-c919-42dc-b0ed-146efa5a68b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PDF Viewer</value>
      <webElementGuid>c40ace4b-9bb6-4214-87fd-326e25e61418</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;r1lTjm-cap&quot;)</value>
      <webElementGuid>4c86612f-25d4-473e-9990-29a1be88a06c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='r1lTjm-cap']</value>
      <webElementGuid>e795bf94-b9f6-4850-b42e-e56409037957</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='r1lTjm']/div</value>
      <webElementGuid>62dbd9ca-7be5-4dd1-b84d-31d1359ceabb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Start'])[1]/following::div[3]</value>
      <webElementGuid>e60855f6-d262-44b1-9a56-0b2f8ed30ccb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Finish'])[1]/following::div[15]</value>
      <webElementGuid>f6526c53-8a1d-42ca-a88b-16d5ec512de8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PDF Viewer']/parent::*</value>
      <webElementGuid>0bc1c13b-5c1f-4a5a-ae97-78d370a0326c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div</value>
      <webElementGuid>71339817-095b-4aaa-80be-990c10b1a2cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'r1lTjm-cap' and (text() = 'PDF Viewer' or . = 'PDF Viewer')]</value>
      <webElementGuid>3b358835-7c0f-4646-b206-4e10388b3c36</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
