<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Pekerjaan dimulai</name>
   <tag></tag>
   <elementGuidId>6bf764ce-dc2c-4480-950f-81086fe68872</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='cRFM800']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cRFM800</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Pekerjaan dimulai. Apakah Anda ingin mencetak Perintah Kerja Bengkel ?&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d5caad99-e7c9-4266-a6fc-ff9e3879412b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cRFM800</value>
      <webElementGuid>902abfa3-ca2e-4a8f-86d8-43b674e101e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-label</value>
      <webElementGuid>ffe2b9db-e0d5-4f54-ad7e-22a32edd3f1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pekerjaan dimulai. Apakah Anda ingin mencetak Perintah Kerja Bengkel ?</value>
      <webElementGuid>ac2a6388-78b7-4ad1-805e-497d64cf7f98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cRFM800&quot;)</value>
      <webElementGuid>ace32220-b4cc-41ab-a24d-d30801d4d920</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='cRFM800']</value>
      <webElementGuid>81e1564a-16bf-448f-84a4-785e1f18cb72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cRFM700']/span</value>
      <webElementGuid>c55063c7-293b-4f9d-b191-169a658f1b41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Question'])[1]/following::span[1]</value>
      <webElementGuid>0fdf8461-f6cd-47a6-a473-4d798c6422b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Start'])[1]/following::span[1]</value>
      <webElementGuid>116de438-7fb4-487f-8c94-0b6080031695</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yes'])[1]/preceding::span[1]</value>
      <webElementGuid>fa839955-6448-4588-92bb-7ff3c21d3357</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[1]/preceding::span[1]</value>
      <webElementGuid>f8b3c26a-8e36-4184-887e-31cbcb263338</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pekerjaan dimulai. Apakah Anda ingin mencetak Perintah Kerja Bengkel ?']/parent::*</value>
      <webElementGuid>c750bf06-df07-494f-ad58-f7ebc76b2e7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/div/span</value>
      <webElementGuid>d5977466-f869-432f-9a16-90da6cefb011</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'cRFM800' and (text() = 'Pekerjaan dimulai. Apakah Anda ingin mencetak Perintah Kerja Bengkel ?' or . = 'Pekerjaan dimulai. Apakah Anda ingin mencetak Perintah Kerja Bengkel ?')]</value>
      <webElementGuid>4c52dee3-bbcc-4a0b-9254-3b59e218515f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
