<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>popup_Work Order Finish</name>
   <tag></tag>
   <elementGuidId>e7312d42-cdee-45de-91fa-def71f00ba53</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='bPIX900']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#bPIX900</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#bPIX900-chdex div</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1f6f62ae-d543-4820-b322-0d340417d96c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bPIX900</value>
      <webElementGuid>cc65da9e-1233-4755-82b4-a9bc6cc91f2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-messagebox z-div</value>
      <webElementGuid>0fddc425-37c0-4f3c-94bc-d567f3dba3a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Finish</value>
      <webElementGuid>368fb4eb-f01e-4971-b88f-c12eecd3c061</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bPIX900&quot;)</value>
      <webElementGuid>c8b1183b-cad1-461a-97c0-7bb49d12bf2b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='bPIX900']</value>
      <webElementGuid>2f524c93-bdb4-4f50-b06e-4d4457a22aef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='bPIX900-chdex']/div</value>
      <webElementGuid>63088839-553c-42d3-80f5-e23ea48383c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ZK'])[1]/following::div[3]</value>
      <webElementGuid>c392b0a2-1741-4b39-b89c-603106baea0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OK'])[1]/preceding::div[2]</value>
      <webElementGuid>1b1a564a-16b7-4a8f-8424-053b079e08cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/table/tbody/tr/td[3]/div</value>
      <webElementGuid>8d7de5f1-2340-4c6f-ad80-eb1d72ec22a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'bPIX900' and (text() = ' Work Order ID WO-X6979-24-12-00009 Finish' or . = ' Work Order ID WO-X6979-24-12-00009 Finish')]</value>
      <webElementGuid>d6d6d826-f381-4518-8787-512a1a268b63</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
