<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Alasan Hold Work Order</name>
   <tag></tag>
   <elementGuidId>acb801be-88bc-435d-96c4-4422b23eb774</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[1]/div[6]/div[1]/div[4]/div[1]/div[1]/div[1]/div[1]/select[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#r1lT2n</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=combobox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>8b1a201a-d9f2-4fe9-a212-fbb7de78b1ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>r1lT2n</value>
      <webElementGuid>f71e2ae4-c3a6-4884-9cc7-bb2afca9be86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>ac453b53-f0cd-451e-a13b-64a092023977</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>selectedindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>4080635b-e7ce-438c-91b1-7f20ba5af626</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sparepart Tidak TersediaPekerjaan LuarPekerjaan Belum Selesai</value>
      <webElementGuid>c7dc102d-b304-4e62-8d6a-8b1d0fcbaef7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;r1lT2n&quot;)</value>
      <webElementGuid>55c1391f-e018-4c33-9b43-76c2fa632c26</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='r1lT2n']</value>
      <webElementGuid>65158656-b82f-48c7-90c5-35e1b7105a78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='r1lT1n']/select</value>
      <webElementGuid>41795fb7-9c7b-47be-b7c9-93372a588340</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alasan Hold WO'])[2]/following::select[1]</value>
      <webElementGuid>7792a91d-022c-4bf1-a21d-5ef30e684933</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='X'])[2]/following::select[1]</value>
      <webElementGuid>5f1653d9-1202-4688-a4c8-e366aea1659d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nomor Pekerjaan'])[1]/preceding::select[1]</value>
      <webElementGuid>87faa2ef-ab23-4ec3-a00c-89de4f7b0ede</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama Pekerjaan Luar'])[1]/preceding::select[1]</value>
      <webElementGuid>37b76c5b-f5cf-4187-a816-c5ae7be2861f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>ffe41ce1-fe9b-4d6b-8456-8e8567b47688</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'r1lT2n' and (text() = 'Sparepart Tidak TersediaPekerjaan LuarPekerjaan Belum Selesai' or . = 'Sparepart Tidak TersediaPekerjaan LuarPekerjaan Belum Selesai')]</value>
      <webElementGuid>e08ff273-34d5-432b-bb6e-621032bcf20e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
