<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Resume Work Order</name>
   <tag></tag>
   <elementGuidId>d99bb08e-6e36-4670-8930-d124e9970124</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='i82Qf80']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#i82Qf80</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;WO-X6979-23-11-00006 Z 8 X 23-Nov-2023 BACHTIAR YORK BEAT SPORTY CW BK LENI NUR AENI&quot;i] >> internal:role=button >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>39a1a578-8781-4c4f-8934-bfbffe322bb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f72bbe53-f505-4eb0-84bf-f8b21abdc9ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>i82Qf80</value>
      <webElementGuid>e58b6414-53cd-437b-b18c-5a9d3719af05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-button</value>
      <webElementGuid>a7b51824-d68b-41ad-9c66-52e0a483ceb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//body[1]/div[2]/div[1]/div[3]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[3]/div[1]/div[1]/div[1]/div[3]/table[1]/tbody[1]/tr[1]/td[9]/div[1]/div[1]/div[1]/button[1]</value>
      <webElementGuid>686fa4cd-ce29-4db7-aab5-64e0f7d28b12</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='i82Qf80']</value>
      <webElementGuid>ab805f27-3952-4ced-8f66-aedcef21af7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='i82Qg80']/button</value>
      <webElementGuid>154263bd-0947-454f-a0d5-8bf32a796885</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LENI NUR AENI'])[1]/following::button[2]</value>
      <webElementGuid>5951fe9e-071b-4571-8186-43b5641784b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BK'])[1]/following::button[2]</value>
      <webElementGuid>3894990b-3c24-40d9-ab72-a173da0b2d84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WO-X6979-00001879'])[1]/preceding::button[1]</value>
      <webElementGuid>29a7e3f6-d2dc-433b-8a6e-c0d9b9f44377</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='D 2414 SAZ'])[1]/preceding::button[1]</value>
      <webElementGuid>b0c8d88f-7e6f-4425-a346-3d64a28780c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[9]/div/div/div/button</value>
      <webElementGuid>e97c3f8a-6d14-4121-9778-0f345cc1b6bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'i82Qf80']</value>
      <webElementGuid>e2043e3e-1b98-4b10-b13c-474b76782a2a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
