<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Close Data Work Order</name>
   <tag></tag>
   <elementGuidId>5088e12e-0109-4d9c-a55a-e6bb2f2c2234</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//body[1]/div[4]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/button[1][count(. | //*[(text() = 'X' or . = 'X')]) = count(//*[(text() = 'X' or . = 'X')])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='xCLQo70']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#xCLQo70</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;X&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>dfbdbde8-52ef-417d-8049-3f4fb093320b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8fb5d550-205d-47fe-805c-72d1f7b3f436</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xCLQo70</value>
      <webElementGuid>25db6cbe-2e63-4ea8-b8c0-633fb2509853</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-close</value>
      <webElementGuid>5685fcb8-b09c-4b9e-8e8f-3d388d351143</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>X</value>
      <webElementGuid>e1ea47c8-d5d4-4fb1-984c-253bfa4c2aee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//body[1]/div[4]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/button[1]</value>
      <webElementGuid>4e612ca0-27c8-4c62-9071-12fd7e44a3b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='xCLQo70']</value>
      <webElementGuid>523c6ccb-686c-4bbd-8dc6-4e4520b28ffa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='xCLQp70']/button</value>
      <webElementGuid>9a56e835-eae3-4df3-9c12-304338de34d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data Work Order'])[1]/following::button[1]</value>
      <webElementGuid>84aaff4b-8841-45ad-b771-ada5889d2ed4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data Work Order'])[2]/preceding::button[1]</value>
      <webElementGuid>8ee01623-56f8-41a5-9ba6-8fe03d3782c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data Pembawa'])[1]/preceding::button[1]</value>
      <webElementGuid>e27ae1d4-b715-4584-a943-ad98f69ba7c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='X']/parent::*</value>
      <webElementGuid>9e20c6ed-0030-4c3d-9566-43a04e8f1cac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button</value>
      <webElementGuid>580ee1fd-60d5-44a5-81c0-1be202d1da23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'xCLQo70' and (text() = 'X' or . = 'X')]</value>
      <webElementGuid>44cdc270-a0bf-42e5-961f-b2fd21293870</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
