<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_No. Work Order</name>
   <tag></tag>
   <elementGuidId>d5b2494a-833a-4841-a9c6-967d7d41d1f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cAvTbn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='cAvTbn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;WO-X6979-00001811&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>cacb1c01-98c0-468a-b28d-69b174461eba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cAvTbn</value>
      <webElementGuid>66d6cc1f-1738-4797-bdff-5fdf6d822e31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-label</value>
      <webElementGuid>a4958642-2ecf-413e-985e-f5ff573cef15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>${nowoid}</value>
      <webElementGuid>4d8ef5fc-615d-453f-acd7-f6aa7f9aee28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//body[1]/div[2]/div[1]/div[3]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[3]/div[1]/div[1]/div[1]/div[3]/table[1]/tbody[1]/tr[1]/td[1]/div[1]/span[1]</value>
      <webElementGuid>b9af4ed7-58fb-4bdb-b834-7ec3c475449a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='cAvTbn']</value>
      <webElementGuid>ef2df640-8037-4d8e-bb8b-354f363fb112</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cAvTbn-cell']/span</value>
      <webElementGuid>879f786a-db82-4902-b667-039ed64d0257</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NIDA NURUL AULYA'])[1]/following::span[2]</value>
      <webElementGuid>6dda359d-1efc-4a4d-947f-103ab0f9f35a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BK'])[2]/following::span[3]</value>
      <webElementGuid>c689ab42-9fee-4614-b1fd-1bc5eb862c97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='F 1655 ABC'])[1]/preceding::span[1]</value>
      <webElementGuid>6668f8a6-aa37-4860-aab2-0a75a93edbd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SUPRIYANTO YOKS'])[1]/preceding::span[3]</value>
      <webElementGuid>bc3e8b51-7199-4138-8082-15d50d90dfbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='WO-X6979-00001811']/parent::*</value>
      <webElementGuid>28706e31-c9c1-4f5c-9316-50c16abbb914</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/div/span</value>
      <webElementGuid>768f6c62-c067-4686-b657-c40937c2f9e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'cAvTbn' and (text() = 'WO-X6979-00001811' or . = 'WO-X6979-00001811')]</value>
      <webElementGuid>f96511fd-0dbf-44a0-a601-73e247726b20</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
