<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Hold Work Order Monitoring</name>
   <tag></tag>
   <elementGuidId>3c486aba-2cb2-4cdf-b290-a1fa65cda86c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#l3yXvj</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='l3yXvj']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Hold Work Order Monitoring&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>71ae851c-f2a7-4d54-8707-4de4db90373b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>l3yXvj</value>
      <webElementGuid>54f280bc-9177-4bb0-a109-87aa3abefd0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>1274d4f9-3656-47db-badd-c9a603e4e771</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hold Work Order Monitoring</value>
      <webElementGuid>e2490664-43b4-425c-8cd1-e8a742e5e1b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;l3yXvj&quot;)</value>
      <webElementGuid>7d95fb97-5f51-4a56-bf75-2f0b653090f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='l3yXvj']</value>
      <webElementGuid>845e69ca-4934-48fe-9ff2-6e4f9ba0c0ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p[@id='l3yXtj']/span</value>
      <webElementGuid>b1724a35-e79c-42e7-bcb7-2585da07c1be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Work Order'])[3]/following::span[1]</value>
      <webElementGuid>3d4b884c-6e8e-46eb-868b-b370e39df610</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pelindungan Data Pribadi'])[2]/following::span[2]</value>
      <webElementGuid>5ae692dd-df41-425e-973d-2824f0cdc076</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Refresh'])[1]/preceding::span[1]</value>
      <webElementGuid>c0e87d97-db8d-419a-b2f9-d503c7a3f57a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih :'])[1]/preceding::span[1]</value>
      <webElementGuid>aef62c99-f82a-496c-9f8f-8bc18bcbd9ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Hold Work Order Monitoring']/parent::*</value>
      <webElementGuid>c485601f-74f4-42a4-a95b-fbb3a632b132</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/p/span</value>
      <webElementGuid>877a6327-d113-4864-b782-4b0df59cf605</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'l3yXvj' and (text() = 'Hold Work Order Monitoring' or . = 'Hold Work Order Monitoring')]</value>
      <webElementGuid>e62da7c0-4ea9-47e2-a137-dc7d6cf07408</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
