<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Ok Panduan Service Visit</name>
   <tag></tag>
   <elementGuidId>3c5904a0-5666-402b-8b1e-266f7ae434f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//body[1]/div[4]/div[1]/div[4]/div[1]/div[1]/button[1][count(. | //*[(text() = 'OK' or . = 'OK')]) = count(//*[(text() = 'OK' or . = 'OK')])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value> </value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#g3BQt40</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;OK&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b6ef14ef-280d-4a96-b15b-7539323010bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e33e7d14-bfca-4226-85d0-ac9b1cefd364</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>g3BQt40</value>
      <webElementGuid>7efcdff7-7955-4ba7-affd-13d6d9aff545</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-button</value>
      <webElementGuid>c2664a08-a7a4-4f4f-9740-e3cb33fbddb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OK</value>
      <webElementGuid>6599f8c6-62a9-474c-889b-4a1b8797ae07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//body[1]/div[4]/div[1]/div[4]/div[1]/div[1]/button[1]</value>
      <webElementGuid>3133ea8b-6ab1-4df4-b494-30229c0d4380</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='g3BQt40']</value>
      <webElementGuid>b2b2c686-1bba-4afb-bfa7-d2cfa944c206</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='g3BQq40']/button</value>
      <webElementGuid>1d1edd46-7371-411f-aaf2-9e5de98b2123</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='[ 1 - 4 / 4 ]'])[1]/following::button[1]</value>
      <webElementGuid>1b877f73-69ad-4d6b-a4e8-d0d79eca766e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='/ 1'])[7]/following::button[1]</value>
      <webElementGuid>ff99e931-2cc3-4e7a-aa00-6b4b9682c5b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='OK']/parent::*</value>
      <webElementGuid>95b8d236-88d6-470a-b3fc-7aacd3e44e4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[4]/div/div/button</value>
      <webElementGuid>c57410f2-cec7-47a0-b069-7d6043f8a92a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'g3BQt40' and (text() = 'OK' or . = 'OK')]</value>
      <webElementGuid>388aa165-63b4-408c-9b67-488853434479</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
