<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Cek Promo</name>
   <tag></tag>
   <elementGuidId>c86ed740-5764-44cb-84d2-1319388b7619</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;g3BQvn&quot;)[count(. | //*[(text() = 'Cek Promo' or . = 'Cek Promo')]) = count(//*[(text() = 'Cek Promo' or . = 'Cek Promo')])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='g3BQvn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#g3BQvn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Cek Promo&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>39da6f20-406c-4965-8bbb-5f16137c4f8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d9083083-6209-4d98-b730-cf30d8806f91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>g3BQvn</value>
      <webElementGuid>25eb969b-38fe-4b20-a4af-2ec95d3c7b3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-button</value>
      <webElementGuid>d412a756-75e5-4fe7-b1f5-f73ab2c232fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cek Promo</value>
      <webElementGuid>bb7b9323-6f33-4b4e-9ea2-0b50a1d821bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//body[1]/div[2]/div[1]/div[3]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[4]/div[1]/div[1]/div[1]/div[1]/div[11]/div[2]/div[5]/button[1]</value>
      <webElementGuid>28cee24c-aa33-420d-b329-9c16b5591902</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='g3BQvn']</value>
      <webElementGuid>e3e7edd7-9144-4d11-a5f4-310498c06df0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='g3BQsn']/button</value>
      <webElementGuid>1134bd61-441f-4d32-abd5-8c03eb8579a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PROMO'])[1]/following::button[1]</value>
      <webElementGuid>a0d785cb-d21f-4c94-8d41-114a74f10b82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp.'])[36]/following::button[1]</value>
      <webElementGuid>54439fe8-214a-4e53-9a86-834be7d671cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama Program'])[1]/preceding::button[1]</value>
      <webElementGuid>ac325544-8de6-4218-9a86-d1eb152b09bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total Diskon'])[1]/preceding::button[1]</value>
      <webElementGuid>e131a85e-b26b-46c7-9dae-9335e831020d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cek Promo']/parent::*</value>
      <webElementGuid>24810db5-4d5d-4f35-8b61-e7bbef609dd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/button</value>
      <webElementGuid>cdafc3b8-263d-4030-be93-35beebec2c2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'g3BQvn' and (text() = 'Cek Promo' or . = 'Cek Promo')]</value>
      <webElementGuid>f5f7db17-e91d-42a8-9889-f35d56ad5c63</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
