<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Set Meter Tangki Bensin</name>
   <tag></tag>
   <elementGuidId>eb5bc3f0-2232-44fb-b185-4abc9b41e6fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[1]/div[2]/div[1]/div[3]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[4]/div[1]/div[1]/div[1]/div[1]/div[10]/div[1]/div[1]/div[6]/div[1]/div[1]/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#g3BQgx0-btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[title=&quot;0&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4786d8dc-9b3c-4761-a570-fc8cc15fc034</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>g3BQgx0-btn</value>
      <webElementGuid>9f1e1120-e16e-4878-8b54-9f159583fd3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-slider-button</value>
      <webElementGuid>536db61b-66d5-4e00-a673-b9cefc243545</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>722ff636-d419-4213-83ef-98aa41b09986</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;g3BQgx0-btn&quot;)</value>
      <webElementGuid>15d4a4fb-d359-4ebf-88fc-1924da5da203</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='g3BQgx0-btn']</value>
      <webElementGuid>e628549c-7fa5-4034-b396-b238298af73b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='g3BQgx0-inner']/div[2]</value>
      <webElementGuid>e0c4229e-6513-4e17-aca4-c84fa9045425</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/div[6]/div/div/div[2]</value>
      <webElementGuid>2261c1a9-6d8d-451e-81e6-f6dd606c02c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'g3BQgx0-btn' and @title = '0']</value>
      <webElementGuid>6ba5459e-aaa7-49ce-a92d-9b250a886026</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
