<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>canvas_Customer</name>
   <tag></tag>
   <elementGuidId>35c41f63-9297-4dfa-92ae-a9db113b278c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//canvas[@id='customer_sign']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#customer_sign</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#customer_sign</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>canvas</value>
      <webElementGuid>4535f49d-9f64-42c4-aedf-0403be41f46d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100px</value>
      <webElementGuid>4672adee-d509-491e-8310-b41bb738915c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100px</value>
      <webElementGuid>6061e0f6-27ee-41ce-9019-05aa43d450e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>customer_sign</value>
      <webElementGuid>209cf38c-0c66-433d-a7ae-515f734f7660</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseup</name>
      <type>Main</type>
      <value>on_mouse_up('customer_sign',event)</value>
      <webElementGuid>45fe5f92-b014-406f-a2c6-867113a09d42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmousedown</name>
      <type>Main</type>
      <value>on_mouse_down('customer_sign',event)</value>
      <webElementGuid>3f716cdd-b324-446e-9738-1d0af661d256</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmousemove</name>
      <type>Main</type>
      <value>on_mouse_move('customer_sign',event)</value>
      <webElementGuid>c754a8d0-f0c4-42f4-b4b4-2dd40449ff71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ontouchstart</name>
      <type>Main</type>
      <value>on_mouse_down('customer_sign', event)</value>
      <webElementGuid>efba973c-6ea1-48f1-bd93-8a1f8c03c906</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ontouchmove</name>
      <type>Main</type>
      <value>on_touch_move('customer_sign',event)</value>
      <webElementGuid>3f169e64-87f2-4a3c-aac1-ddfc5b3e4cd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ontouchend</name>
      <type>Main</type>
      <value>on_mouse_up('customer_sign',event)</value>
      <webElementGuid>ca04cbc2-3956-46fa-a628-3df1ccf193ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;customer_sign&quot;)</value>
      <webElementGuid>7be6f875-a610-4a28-8e21-8991dd3c27d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//canvas[@id='customer_sign']</value>
      <webElementGuid>f57b4873-bd72-48c2-a30c-11e9f94d3ad4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='g3BQ2r']/canvas</value>
      <webElementGuid>cd149c9d-9486-45df-b2bf-3cfa05557c11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/canvas</value>
      <webElementGuid>7e0c603d-5fa5-4a46-a809-9256da43f3dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//canvas[@id = 'customer_sign']</value>
      <webElementGuid>fb2c89ae-7270-4e63-b614-6181d038ef69</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
