<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama Kota</name>
   <tag></tag>
   <elementGuidId>b7745668-e368-46c2-8157-830c5ab10803</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[1]/div[4]/div[1]/table[1]/tbody[1]/tr[1]/td[1]/table[1]/tbody[1]/tr[1]/td[1]/table[1]/tbody[1]/tr[1]/td[1]/table[1]/tbody[1]/tr[1]/td[1]/input[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#g3BQfm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;Search Nama Kabupaten/Kota KAB. ADM. KEP. SERIBU KOTA ADM. JAKARTA BARAT KOTA ADM. JAKARTA PUSAT KOTA ADM. JAKARTA SELATAN KOTA ADM. JAKARTA TIMUR KOTA ADM. JAKARTA UTARA&quot;i] >> internal:role=textbox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>23042ee6-574c-4f25-921f-bd6f9503c687</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>g3BQfm</value>
      <webElementGuid>5ae33245-4f49-4513-9181-69fb98e8b3f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font-uppercase z-textbox</value>
      <webElementGuid>e24bf825-2200-4d74-9c98-79f84e0eb4c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c7d63384-28c0-4118-ad05-9288297a66be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;g3BQfm&quot;)</value>
      <webElementGuid>6985be65-c1e6-4e71-9c2a-d9c26bdd6d32</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='g3BQfm']</value>
      <webElementGuid>0238d418-d2ab-4027-bf42-e4b9919d50e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='g3BQfm-chdex']/input</value>
      <webElementGuid>792d740d-1351-40d8-904e-b99a03bc16c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr/td/input</value>
      <webElementGuid>debfd78d-df2b-4d67-8386-5e5facc2ff01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'g3BQfm' and @type = 'text']</value>
      <webElementGuid>966dfa80-25a2-4440-b9a6-cecfcab6eec8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
