<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Promo 3</name>
   <tag></tag>
   <elementGuidId>7af22d2e-5625-4293-a883-deaad90b6ce0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='g3BQ4d1-real']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#g3BQ4d1-real</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;SUPREME Rp. 2,500 Tidak&quot;i] >> internal:label=&quot;&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a74f9310-c90c-4f37-ad83-793397276785</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>e7f42b8a-03ff-4a58-b40d-2413886f292f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>g3BQ4d1-real</value>
      <webElementGuid>cdc7a3ea-5d39-4836-b8a9-a45f9e4737fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;g3BQ4d1-real&quot;)</value>
      <webElementGuid>2dd96821-4378-45e3-b927-f637f03e9534</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='g3BQ4d1-real']</value>
      <webElementGuid>ccc3750f-8ed7-4757-897f-234a794ac546</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='g3BQ4d1']/input</value>
      <webElementGuid>45909df1-2999-49f8-8372-5ddd89ff73d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div[3]/table/tbody/tr[3]/td[4]/div/div/span/input</value>
      <webElementGuid>b7c71a5d-a5e4-4252-b3b6-ccb4bd49460e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'g3BQ4d1-real']</value>
      <webElementGuid>f6767b28-6496-41f4-907b-bae77996e429</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
