<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama Provinsi</name>
   <tag></tag>
   <elementGuidId>a5d6207f-0fbe-4214-aa9f-83ffdc6604ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[1]/div[3]/div[1]/table[1]/tbody[1]/tr[1]/td[1]/table[1]/tbody[1]/tr[1]/td[1]/table[1]/tbody[1]/tr[1]/td[1]/table[1]/tbody[1]/tr[1]/td[1]/input[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#g3BQ3m</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;Search Nama Provinsi Bali Bangka-Belitung Banten Bengkulu D I Yogyakarta D K I Jakarta Gorontalo Irian Jaya Barat Jambi Jawa Barat Jawa Tengah Jawa Timur KALIMANTAN UTARA Kalimantan Barat Kalimantan Selatan Kalimantan Tengah Kalimantan Timur Kepulauan Riau Lampung Maluku Maluku Utara Nanggroe Aceh Darussalam Nusa Tenggara Barat Nusa Tenggara Timur Papua Riau Sulawesi Barat Sulawesi Selatan Sulawesi Tengah Sulawesi Tenggara Sulawesi Utara Sumatera Barat Sumatera Selatan Sumatera Utara&quot;i] >> internal:role=textbox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>faf4693f-1450-4682-920d-9bc1931325ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>g3BQ3m</value>
      <webElementGuid>846fc1ed-20c6-443d-8db0-89d771c49114</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font-uppercase z-textbox</value>
      <webElementGuid>da7b7007-a8be-4980-a540-12acbaa7599d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>db187175-145e-4c8c-87d6-acdea075cb5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;g3BQ3m&quot;)</value>
      <webElementGuid>89464dcc-79ed-4639-8c51-dbf7089b2ed1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='g3BQ3m']</value>
      <webElementGuid>164c1fd6-a06a-486a-9119-d5176f8d017b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='g3BQ3m-chdex']/input</value>
      <webElementGuid>35eccf8e-0773-490b-81cf-434a3e4c48c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>b35dff0c-05ed-4afb-a748-14051bafd991</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'g3BQ3m' and @type = 'text']</value>
      <webElementGuid>0c7dd0ab-30f7-402e-849e-834184864719</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
