<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>popup_Data Pembawa</name>
   <tag></tag>
   <elementGuidId>fe3593b0-f803-407c-9c4d-5c43f66e00ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//body[1]/div[4]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[1]/div[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#g3BQ_x0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;ZK Customer dengan nama dwi surahman dua cust berhasil disimpan. OK&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>db6b6403-6094-4780-9b68-1ca024f7af13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>g3BQ_x0</value>
      <webElementGuid>62b9d25c-daff-4fee-8255-a1848ca0cd0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-messagebox-window  z-window z-window-highlighted z-window-shadow</value>
      <webElementGuid>d482a063-ea70-4c47-8dd8-9120da5a7106</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ZK Customer dengan nama</value>
      <webElementGuid>1a65f6fa-9ecd-4071-afbe-704c91bd713e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//body[1]/div[4]</value>
      <webElementGuid>f0a3e59e-6d10-4a12-9213-b7b07292d63e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[1]/following::div[5]</value>
      <webElementGuid>da65a09e-2399-4df8-a697-e51a181acf4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]</value>
      <webElementGuid>b1a5f942-8214-4c30-b366-1320c61a223d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[4]</value>
      <webElementGuid>eadd9c35-7222-436f-9b33-38d0756f47cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
