<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>popup_Input Keluhan</name>
   <tag></tag>
   <elementGuidId>faaf8043-b22a-4171-8b37-8f37ac4b62a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//body[1]/div[5][count(. | //*[(text() = '    Input Keluhan   X      Keluhan START AWAL BERGETARBEREBETISS TIDAK BERFUNGSIKURANG BERTENAGASUARA MESIN BERISIKCVT GETARBENSIN BOROSSUSAH HIDUP DI PAGI HARIPLAT MOTOR BERGETARLAIN-LAIN  Analisa     Kirim' or . = '    Input Keluhan   X      Keluhan START AWAL BERGETARBEREBETISS TIDAK BERFUNGSIKURANG BERTENAGASUARA MESIN BERISIKCVT GETARBENSIN BOROSSUSAH HIDUP DI PAGI HARIPLAT MOTOR BERGETARLAIN-LAIN  Analisa     Kirim')]) = count(//*[(text() = '    Input Keluhan   X      Keluhan START AWAL BERGETARBEREBETISS TIDAK BERFUNGSIKURANG BERTENAGASUARA MESIN BERISIKCVT GETARBENSIN BOROSSUSAH HIDUP DI PAGI HARIPLAT MOTOR BERGETARLAIN-LAIN  Analisa     Kirim' or . = '    Input Keluhan   X      Keluhan START AWAL BERGETARBEREBETISS TIDAK BERFUNGSIKURANG BERTENAGASUARA MESIN BERISIKCVT GETARBENSIN BOROSSUSAH HIDUP DI PAGI HARIPLAT MOTOR BERGETARLAIN-LAIN  Analisa     Kirim')])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='g3BQ5a0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#g3BQ5a0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=&quot;Input Keluhan X Keluhan START AWAL BERGETARBEREBETISS TIDAK BERFUNGSIKURANG BERT&quot;i >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7105f93b-099e-48c8-b9e2-528e446b8695</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>g3BQ5a0</value>
      <webElementGuid>60fa81f3-73e0-45b0-8dd6-94dbfc1b771e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-window z-window-noborder z-window-noheader z-window-modal z-window-shadow</value>
      <webElementGuid>270d985a-6522-42b1-826b-151f336a664d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>    Input Keluhan   X      Keluhan START AWAL BERGETARBEREBETISS TIDAK BERFUNGSIKURANG BERTENAGASUARA MESIN BERISIKCVT GETARBENSIN BOROSSUSAH HIDUP DI PAGI HARIPLAT MOTOR BERGETARLAIN-LAIN  Analisa     Kirim</value>
      <webElementGuid>52a9f82c-5185-4327-9010-2cd1d49acbfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//body[1]/div[5]</value>
      <webElementGuid>d2bcf257-461a-4d55-abc1-25937e38e58a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='g3BQ5a0']</value>
      <webElementGuid>25c863a5-dc34-4602-a695-065f2ecead08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[1]/following::div[3]</value>
      <webElementGuid>05f81f54-2a05-4743-b8aa-e5db1a57371b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]</value>
      <webElementGuid>645e2845-0069-4fc6-b3d4-8cac21b361b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'g3BQ5a0' and (text() = '    Input Keluhan   X      Keluhan START AWAL BERGETARBEREBETISS TIDAK BERFUNGSIKURANG BERTENAGASUARA MESIN BERISIKCVT GETARBENSIN BOROSSUSAH HIDUP DI PAGI HARIPLAT MOTOR BERGETARLAIN-LAIN  Analisa     Kirim' or . = '    Input Keluhan   X      Keluhan START AWAL BERGETARBEREBETISS TIDAK BERFUNGSIKURANG BERTENAGASUARA MESIN BERISIKCVT GETARBENSIN BOROSSUSAH HIDUP DI PAGI HARIPLAT MOTOR BERGETARLAIN-LAIN  Analisa     Kirim')]</value>
      <webElementGuid>1a47721a-cb25-4a94-92f6-071a4245ad96</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
