<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rdr_Ya Spare Part Dibawa</name>
   <tag></tag>
   <elementGuidId>a38320bd-773f-4d4a-9ad8-3364827c8811</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[1]/div[2]/div[1]/div[3]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[4]/div[1]/div[1]/div[1]/div[1]/div[14]/div[1]/div[2]/div[1]/div[1]/span[1]/input[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#g3BQ5q-real</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Ya&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e20f0edb-d4e3-41d2-b455-303dc5dd62fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>826a6922-8e36-4305-ba63-3230a97a65a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>g3BQ5q-real</value>
      <webElementGuid>21c7df9f-3852-4a15-9df8-34a42644d70f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>_pgdmgond</value>
      <webElementGuid>67ef6241-d6de-4801-875b-89414b1a7bce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>YES</value>
      <webElementGuid>42e9f7f9-58ba-4ff6-87a5-17b1ed5e9e19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;g3BQ5q-real&quot;)</value>
      <webElementGuid>bcd46f83-88ce-453c-b936-72c89ece7f14</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='g3BQ5q-real']</value>
      <webElementGuid>d5da2333-b67f-4ce1-875d-58e2817da943</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='g3BQ5q']/input</value>
      <webElementGuid>c270c615-4a54-42f8-b2e5-f39a2a74daf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div/div[2]/div/div/span/input</value>
      <webElementGuid>1c73ebb2-0a13-455d-9f2e-e475e7474787</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'g3BQ5q-real' and @name = '_pgdmgond']</value>
      <webElementGuid>58b6a05b-9a4b-420d-9a98-78a24d6befc4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
