<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rdr_Konfirmasi dahulu melalui No Telp</name>
   <tag></tag>
   <elementGuidId>5066844e-bded-4537-942e-2f343c59777b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='g3BQzp-real']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#g3BQzp-real</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Konfirmasi dahulu melalui No. Telp :&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>40c6797d-e5f8-4d3c-9ecd-6edbc61ef324</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>0499964c-8145-40fa-8ece-fc388c4814d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>g3BQzp-real</value>
      <webElementGuid>7047da0e-c178-4c1d-9414-4eeedf312e8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>_pgnt0ph1</value>
      <webElementGuid>ae20a646-5f71-42a5-8f6e-42fd084a5fe4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>KONFIRMASI</value>
      <webElementGuid>86840bc0-2d50-469c-8a2f-3c659ea1a8d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;g3BQzp-real&quot;)</value>
      <webElementGuid>d0a6329c-1a21-4c7c-9824-287defe3aadb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='g3BQzp-real']</value>
      <webElementGuid>4d52f3c8-70d3-4622-af15-fa66a594d450</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='g3BQzp']/input</value>
      <webElementGuid>9109f17d-c1dd-4a40-9531-e375b5b2a0b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div/div/div[2]/div/span/input</value>
      <webElementGuid>43250604-8ad7-471a-ac10-cf8c7e0cab49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'g3BQzp-real' and @name = '_pgnt0ph1']</value>
      <webElementGuid>e8b8997e-8f60-41fc-9f00-f7ed27027d77</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
