<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Keluhan</name>
   <tag></tag>
   <elementGuidId>337a4b60-dfdb-48b8-844a-0aa3492bb710</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'g3BQka0' and (text() = 'START AWAL BERGETARBEREBETISS TIDAK BERFUNGSIKURANG BERTENAGASUARA MESIN BERISIKCVT GETARBENSIN BOROSSUSAH HIDUP DI PAGI HARIPLAT MOTOR BERGETARLAIN-LAIN' or . = 'START AWAL BERGETARBEREBETISS TIDAK BERFUNGSIKURANG BERTENAGASUARA MESIN BERISIKCVT GETARBENSIN BOROSSUSAH HIDUP DI PAGI HARIPLAT MOTOR BERGETARLAIN-LAIN')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[1]/div[5]/div[1]/div[3]/div[1]/div[1]/div[1]/select[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#g3BQka0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#g3BQka0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>9698a25a-9f65-40b6-a5ad-99f979db5b68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>g3BQka0</value>
      <webElementGuid>48f5d9aa-828e-469c-9e09-e395cabd4591</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>4cf5e39c-b515-4895-975d-1dbabb232cbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>START AWAL BERGETARBEREBETISS TIDAK BERFUNGSIKURANG BERTENAGASUARA MESIN BERISIKCVT GETARBENSIN BOROSSUSAH HIDUP DI PAGI HARIPLAT MOTOR BERGETARLAIN-LAIN</value>
      <webElementGuid>310ff966-3d57-42d7-99dc-d8b2b0f6e546</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;g3BQka0&quot;)</value>
      <webElementGuid>24e04df3-3773-47d7-b3ed-cdd71c5b3bce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='g3BQka0']</value>
      <webElementGuid>27930652-e852-481d-9ba7-a677fd40c893</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='g3BQia0']/select</value>
      <webElementGuid>68d3da36-0ffe-46ae-833b-e5c18155de8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keluhan'])[1]/following::select[1]</value>
      <webElementGuid>ce4a5651-1ebe-46f4-991d-6184d30c42d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='X'])[2]/following::select[1]</value>
      <webElementGuid>71a5d891-7274-448e-b971-f29f65fc2b54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Analisa'])[2]/preceding::select[1]</value>
      <webElementGuid>30dd2bc3-4585-404b-a85b-3c8b35f4f8e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kirim'])[1]/preceding::select[1]</value>
      <webElementGuid>c74e0930-371c-4f95-98d9-e5ca82041275</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/select</value>
      <webElementGuid>1c91a51b-e68b-4940-9ae7-7d3e8d6edf30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'g3BQka0' and (text() = 'START AWAL BERGETARBEREBETISS TIDAK BERFUNGSIKURANG BERTENAGASUARA MESIN BERISIKCVT GETARBENSIN BOROSSUSAH HIDUP DI PAGI HARIPLAT MOTOR BERGETARLAIN-LAIN' or . = 'START AWAL BERGETARBEREBETISS TIDAK BERFUNGSIKURANG BERTENAGASUARA MESIN BERISIKCVT GETARBENSIN BOROSSUSAH HIDUP DI PAGI HARIPLAT MOTOR BERGETARLAIN-LAIN')]</value>
      <webElementGuid>a830f07e-0172-4b16-98e0-399357c9d804</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
