<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Close Popup Data Pembawa</name>
   <tag></tag>
   <elementGuidId>8b9cb7ef-39cc-4309-8c15-af465d144b1f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='g3BQ_x0-close']/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.z-icon-times</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[title=&quot;Close&quot;i] >> i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>ffa36b15-e217-4f79-ba12-9833834f5a14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-icon-times</value>
      <webElementGuid>c296f8eb-a6a0-40b3-be6f-2b4685e60b45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;g3BQ_x0-close&quot;)/i[@class=&quot;z-icon-times&quot;]</value>
      <webElementGuid>97340788-8023-4896-963e-1bb87607278d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='g3BQ_x0-close']/i</value>
      <webElementGuid>8185ead9-591b-46c8-8b2d-b25d6620f074</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/i</value>
      <webElementGuid>2a209932-6729-416c-a073-6a450308e44b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
