<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Kirim Input Keluhan</name>
   <tag></tag>
   <elementGuidId>d10912cd-104d-49e0-92be-40f83b550fac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='g3BQsa0']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;g3BQsa0&quot;)[count(. | //*[(text() = 'Kirim' or . = 'Kirim')]) = count(//*[(text() = 'Kirim' or . = 'Kirim')])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#g3BQsa0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Kirim&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1951ee24-e360-4dd0-a2fb-6713c7415a85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>974147c6-f4c1-4e93-80ee-4f496f47d62b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>g3BQsa0</value>
      <webElementGuid>347514d2-9ee0-44d7-a064-3ea044223c43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-button</value>
      <webElementGuid>3bbf1167-e7b3-4260-8460-ddeca0b8cee2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kirim</value>
      <webElementGuid>a35b6cdf-03a8-4c0b-a746-170f32e96c9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//body[1]/div[5]/div[1]/div[4]/div[1]/div[1]/div[1]/button[1]</value>
      <webElementGuid>0bb8ff1d-4027-49a1-8cb3-817dc89f3fa1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='g3BQsa0']</value>
      <webElementGuid>b00da5ec-accf-4c56-9391-806e3aa1afb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='g3BQta0']/button</value>
      <webElementGuid>bca5ffd9-13a9-4e1b-8438-2a9b1da99661</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Analisa'])[2]/following::button[1]</value>
      <webElementGuid>a9989f23-5e5c-4a11-bf58-5d6e7be07f88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keluhan'])[1]/following::button[1]</value>
      <webElementGuid>f52e6e76-c2c3-4f9e-a6b4-0bbc67482331</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Kirim']/parent::*</value>
      <webElementGuid>2c59dc8d-f8a9-4ab1-bfe9-c7bd85d88620</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[4]/div/div/div/button</value>
      <webElementGuid>15b93e99-e7f7-4d21-bb92-0b1846a95d79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'g3BQsa0' and (text() = 'Kirim' or . = 'Kirim')]</value>
      <webElementGuid>815a0960-feb5-46fc-8265-9eb0f21b686c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
