<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>canvas_SA</name>
   <tag></tag>
   <elementGuidId>88ce8f4f-a5e1-4515-aae3-de633ade8e26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//canvas[@id='sa_sign']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#sa_sign</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#sa_sign</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>canvas</value>
      <webElementGuid>d16d42a3-e59a-434f-9435-60f9b11ee7c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100px</value>
      <webElementGuid>3fd61d9a-518a-4565-bbb5-228e2796f99a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100px</value>
      <webElementGuid>f93ac1d9-641e-4505-90c2-0b0afef35b59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sa_sign</value>
      <webElementGuid>8ada0de6-50de-4117-9e2a-64b1ab88c351</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseup</name>
      <type>Main</type>
      <value>on_mouse_up('sa_sign',event)</value>
      <webElementGuid>ad43d777-08e7-497a-9f92-fc2971cdbdcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmousedown</name>
      <type>Main</type>
      <value>on_mouse_down('sa_sign',event)</value>
      <webElementGuid>c4d417ff-8834-4baf-9b8a-55f889d512d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmousemove</name>
      <type>Main</type>
      <value>on_mouse_move('sa_sign',event)</value>
      <webElementGuid>1ae00eab-d184-45f0-a965-08946269719c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ontouchstart</name>
      <type>Main</type>
      <value>on_mouse_down('sa_sign',event)</value>
      <webElementGuid>c2f16b70-3856-48a6-9a01-3df42a88ad98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ontouchmove</name>
      <type>Main</type>
      <value>on_touch_move('sa_sign',event)</value>
      <webElementGuid>f10c300e-f74e-4239-946d-ab1076683bd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ontouchend</name>
      <type>Main</type>
      <value>on_mouse_up('sa_sign',event)</value>
      <webElementGuid>740d1b61-89b2-4abe-95ab-3bab54f03436</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sa_sign&quot;)</value>
      <webElementGuid>7ef7230f-af5e-48f7-905e-9d74ca0824ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//canvas[@id='sa_sign']</value>
      <webElementGuid>695453a4-e7aa-4c09-8556-bc9b117a3e39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='g3BQqd0']/canvas</value>
      <webElementGuid>55a31fce-bee0-4a1c-a905-ea0f4fc35a71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//canvas</value>
      <webElementGuid>5e48e6bf-95cf-4c14-a612-dd4437c21102</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//canvas[@id = 'sa_sign']</value>
      <webElementGuid>8502493a-5da0-4d55-bea7-5579e0694a57</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
