<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Promo 2</name>
   <tag></tag>
   <elementGuidId>23e19d0c-3c4c-4694-823a-d258345e9a63</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='g3BQ0c1-real']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#g3BQ0c1-real</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;DISKON SERVICE 20% UNTUJ OJOL Rp. 44,000 Ya&quot;i] >> internal:label=&quot;&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d1935566-5ebe-4255-89ae-4e1d1475fcb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>8994b1a6-6595-4f54-ad97-cbf4a294f5b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>g3BQ0c1-real</value>
      <webElementGuid>6f0786f2-9175-4d82-a2e2-686f72249f74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;g3BQ0c1-real&quot;)</value>
      <webElementGuid>b314ed44-329d-442e-add8-6ab41ce23515</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='g3BQ0c1-real']</value>
      <webElementGuid>e299a558-8110-46bb-8f5a-d0b194c01945</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='g3BQ0c1']/input</value>
      <webElementGuid>548269a4-5210-48ea-8aad-adeead6d44a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div[3]/table/tbody/tr[2]/td[4]/div/div/span/input</value>
      <webElementGuid>80a28700-2147-443f-9ec3-63bfb657032f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'g3BQ0c1-real']</value>
      <webElementGuid>0299dc7e-fe99-4e8d-ac33-d3ecd694772b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
