<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>list_Jasa Service</name>
   <tag></tag>
   <elementGuidId>f211d93b-de84-4906-b4cf-cde0c967a845</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='g3BQ_n1-cell']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#g3BQ_n1-cell</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;ASS 1 PERAWATAN&quot;i] >> div</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8153aeea-3184-4f43-a4ed-5c68872b532d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>g3BQ_n1-cell</value>
      <webElementGuid>4b751d22-ea40-41ff-971f-9ac84b7cf4b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-row-content</value>
      <webElementGuid>8790a2e3-b03f-4983-bdb2-442b47809b49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ASS 1 PERAWATAN</value>
      <webElementGuid>c83d28b0-ff9b-4a67-a275-a3dd5fa817cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;g3BQ_n1-cell&quot;)</value>
      <webElementGuid>533a38c1-9c54-4564-bbc9-9c156f09f140</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='g3BQ_n1-cell']</value>
      <webElementGuid>94af4244-380b-44e1-8d74-5a08a04fbd1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='g3BQ_n1-chdextr']/div</value>
      <webElementGuid>4b2cb30f-3c50-425e-8dca-98db414458fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ahass ID'])[1]/following::div[6]</value>
      <webElementGuid>04146ad3-589a-4561-9b30-b02ec8c6c31f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipe Jasa'])[1]/following::div[8]</value>
      <webElementGuid>b6334440-d7cd-475f-93f3-8c30bfd3cf71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SATUAN'])[1]/preceding::div[1]</value>
      <webElementGuid>7de340bf-1c83-43de-9bfe-8b37d05b92ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div[3]/table/tbody/tr/td[3]/div</value>
      <webElementGuid>61ec14bc-eb73-4050-a0d5-370afe8104f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'g3BQ_n1-cell' and (text() = 'ASS 1 PERAWATAN' or . = 'ASS 1 PERAWATAN')]</value>
      <webElementGuid>3631f3b7-dc68-46af-9ee5-d0b480f304f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
