<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rdr_Tidak Spare Part</name>
   <tag></tag>
   <elementGuidId>5c2e01f0-cc89-4420-ad94-fded0a638b18</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='g3BQ7q-real']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#g3BQ7q-real</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Tidak&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dccb5ede-ce07-4a4c-901a-0b6d5f15c50b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>91ef97ab-9bef-47ed-8d91-bc42b1a580c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>g3BQ7q-real</value>
      <webElementGuid>16b2d981-493c-471d-ba28-8bca3c135143</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>_pgdmgond</value>
      <webElementGuid>06c0c46a-fa91-4a59-bdf3-3b32e9ec9c42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>NO</value>
      <webElementGuid>58b23972-1c07-4fdd-9715-da2042ad5aa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;g3BQ7q-real&quot;)</value>
      <webElementGuid>9dfbdac2-d4f7-4b79-b384-663e99f3ba2f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='g3BQ7q-real']</value>
      <webElementGuid>29f6b270-57c4-4370-93e0-5bc8c3e136be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='g3BQ7q']/input</value>
      <webElementGuid>a3eaf611-35a7-45fc-92d5-99d60ad3fbf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div/div[2]/div/div[2]/span/input</value>
      <webElementGuid>cf24a9a2-d0f2-4fc4-8c98-e2d18832c170</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'g3BQ7q-real' and @name = '_pgdmgond']</value>
      <webElementGuid>a5d76a16-5a0c-4cfe-ba0d-d7aa204478bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
