<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rdr_Langsung dikerjakan oleh mekanik</name>
   <tag></tag>
   <elementGuidId>7711eca8-9223-486d-9805-00bd50efe562</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[1]/div[2]/div[1]/div[3]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[4]/div[1]/div[1]/div[1]/div[1]/div[14]/div[1]/div[1]/div[2]/span[2]/input[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#g3BQ0q-real</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Langsung dikerjakan oleh mekanik / diganti suku cadangnya&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2d532e6e-eeff-4652-a412-251fba76810e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>9ae8dcc7-22d0-4f91-a85f-e7e068694185</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>g3BQ0q-real</value>
      <webElementGuid>8dba428b-4977-4f59-8243-60911a662509</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>_pgnt0ph1</value>
      <webElementGuid>a0810d70-d84e-498b-b0d2-60d819f054b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>LANGSUNG_DIKERJAKAN</value>
      <webElementGuid>a0bf5c6b-6287-40f8-ad22-ec84fa8b30e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;g3BQ0q-real&quot;)</value>
      <webElementGuid>788adc98-a530-43ea-9834-a87a5ec8eec7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='g3BQ0q-real']</value>
      <webElementGuid>42cca971-c123-429d-aa18-df89168ae070</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='g3BQ0q']/input</value>
      <webElementGuid>8fb6cee3-e1bd-4d44-ae8f-3308188e9483</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div/div/div[2]/span[2]/input</value>
      <webElementGuid>31fa3488-fa31-4783-97a7-e0086d43fa4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'g3BQ0q-real' and @name = '_pgnt0ph1']</value>
      <webElementGuid>52cf8091-28e4-44d7-b6af-807a4f872c4f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
