<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Hubungan Pembawa dan Pemilik</name>
   <tag></tag>
   <elementGuidId>f71ae93f-5575-4dc6-9fc9-753803be5d22</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[1]/div[2]/div[1]/div[3]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[4]/div[1]/div[1]/div[1]/div[1]/div[6]/div[1]/div[2]/div[1]/div[1]/select[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#g3BQss1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=combobox >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>ff949fc4-cc78-40b4-ad33-1a94b8f1f3e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>g3BQss1</value>
      <webElementGuid>36c19318-de24-4aa5-bda4-e0571f46d36f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>4bde0d0f-0a63-425e-a99a-00f911687a63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Orang TuaAnakSaudaraKaryawanTemanSuami/IstriLainnyaMilik Sendiri</value>
      <webElementGuid>543ae875-fdda-43ad-97f6-fed019432f95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;g3BQss1&quot;)</value>
      <webElementGuid>f93e0a37-ad4d-4044-a2ca-7729aa7b888f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='g3BQss1']</value>
      <webElementGuid>214493d3-f8ba-4429-8d18-1fa83b993ca9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='g3BQvs1']/select</value>
      <webElementGuid>d24b2cf2-d5ae-4086-b068-aca12dd5a97b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::select[1]</value>
      <webElementGuid>e39bf173-ddf8-4db0-ab95-48bd5824931c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hubungan Pembawa &amp; Pemilik'])[1]/following::select[1]</value>
      <webElementGuid>202f16de-1f36-47f8-b978-9e27a9b7d20d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No Telp / HP'])[1]/preceding::select[1]</value>
      <webElementGuid>41106fc9-75a1-4f3a-a9ce-046cac46d14a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/preceding::select[1]</value>
      <webElementGuid>37acde57-12b7-4966-8a7d-df8001040b1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>03467cf4-a66d-4b85-88cb-42ea38653576</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'g3BQss1' and (text() = 'Orang TuaAnakSaudaraKaryawanTemanSuami/IstriLainnyaMilik Sendiri' or . = 'Orang TuaAnakSaudaraKaryawanTemanSuami/IstriLainnyaMilik Sendiri')]</value>
      <webElementGuid>9dd86d6a-100a-48ad-9201-5a98b71c267d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
