<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Hubungan Pembawa dan Pemilik</name>
   <tag></tag>
   <elementGuidId>f71ae93f-5575-4dc6-9fc9-753803be5d22</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[1]/div[2]/div[1]/div[3]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[4]/div[1]/div[1]/div[1]/div[1]/div[6]/div[1]/div[2]/div[1]/div[1]/select[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#g3BQss1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=combobox >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>cf7349dd-1304-492d-83a6-5d63f11bd3aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>g3BQss1</value>
      <webElementGuid>01c3cf37-ab1d-4c8f-9536-86402bc35168</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>1a9edeef-3de9-4bc7-89c2-d251c8a2fe68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Orang TuaAnakSaudaraKaryawanTemanSuami/IstriLainnyaMilik Sendiri</value>
      <webElementGuid>a44b2a6d-b30d-42e5-bfed-018cb8147eba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;g3BQss1&quot;)</value>
      <webElementGuid>4f4662dc-95f2-4f19-a780-d8be84ec4f70</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='g3BQss1']</value>
      <webElementGuid>ee3e1c21-e593-4edb-a73b-79a7c2e156c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='g3BQvs1']/select</value>
      <webElementGuid>1397fe48-ca38-49fe-9a36-4868c5583c09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::select[1]</value>
      <webElementGuid>5afa0eb0-e23e-493d-846d-f77de9d2014b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hubungan Pembawa &amp; Pemilik'])[1]/following::select[1]</value>
      <webElementGuid>8ab27727-2ddf-4128-a4b3-631a2aa91789</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No Telp / HP'])[1]/preceding::select[1]</value>
      <webElementGuid>896d98b7-126c-400c-865b-7b9db76f03be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/preceding::select[1]</value>
      <webElementGuid>2d47e89f-2179-4276-af0c-042a1338eabd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>63b53830-e07b-4452-b23f-5b966c422d6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'g3BQss1' and (text() = 'Orang TuaAnakSaudaraKaryawanTemanSuami/IstriLainnyaMilik Sendiri' or . = 'Orang TuaAnakSaudaraKaryawanTemanSuami/IstriLainnyaMilik Sendiri')]</value>
      <webElementGuid>b01e6697-60f5-499e-aa29-8dd53ba63837</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
