<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Nama Mekanik</name>
   <tag></tag>
   <elementGuidId>0e2ae971-47f5-476e-b651-f6eac34630bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[1]/div[2]/div[1]/div[3]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[4]/div[1]/div[1]/div[1]/div[1]/div[5]/div[1]/div[1]/div[3]/select[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#g3BQln</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#g3BQln</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>979b305a-ecfc-4c21-a912-5a35e5ced6ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>g3BQln</value>
      <webElementGuid>4f353ca4-7133-44cc-b78c-1f1778800763</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c6af1499-7672-40b5-8a76-2ebdc2daff7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>GENTA YORKSYAMSUL YORKDEDE YOKSDEDE YOKSSYAMSUL YORKBACHTIAR YORKBUDI YORKBUDI YORKSIDIK YOKSBACHTIAR YORKBUDI YORKSIDIK YOKS</value>
      <webElementGuid>c354fcf6-fc83-4daf-ab2b-437cfbc4a73c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;g3BQln&quot;)</value>
      <webElementGuid>21664ac3-a637-4d6f-b44c-8bd59aebe5b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='g3BQln']</value>
      <webElementGuid>8386cf0c-8ee2-4817-848f-4b1bb8616ec2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='g3BQjn']/select</value>
      <webElementGuid>d54f1b92-cc50-4642-bbe5-9b4d5b3025a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Nama Mekanik'])[1]/following::select[1]</value>
      <webElementGuid>26fd0006-1d17-4941-b4e1-844bc1ecc93a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Tipe KPB'])[1]/following::select[2]</value>
      <webElementGuid>e7c71a75-989a-47f3-8b83-096e229c4130</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No. Pit Service'])[1]/preceding::select[1]</value>
      <webElementGuid>c1c718cf-b425-485b-b22d-1dcfe951e5df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipe Pit'])[1]/preceding::select[1]</value>
      <webElementGuid>ee9a63e1-90a7-4a38-8057-2cada754878e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/select</value>
      <webElementGuid>d0bf032d-c815-4b62-8e90-e7aca7247f0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'g3BQln' and (text() = 'GENTA YORKSYAMSUL YORKDEDE YOKSDEDE YOKSSYAMSUL YORKBACHTIAR YORKBUDI YORKBUDI YORKSIDIK YOKSBACHTIAR YORKBUDI YORKSIDIK YOKS' or . = 'GENTA YORKSYAMSUL YORKDEDE YOKSDEDE YOKSSYAMSUL YORKBACHTIAR YORKBUDI YORKBUDI YORKSIDIK YOKSBACHTIAR YORKBUDI YORKSIDIK YOKS')]</value>
      <webElementGuid>715c1869-bb2f-4499-a5d0-30532c51c9dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
