<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Close Redirect Message</name>
   <tag></tag>
   <elementGuidId>783f472c-4e47-4ca2-a1b5-e91e74876eb1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;p0BQe-close&quot;)/i[@class=&quot;z-icon-times&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.z-icon-times</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[1]/div[4]/div[1]/div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>b3cfa71f-16b5-4097-b63d-a5769783f051</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-icon-times</value>
      <webElementGuid>db8105e9-125d-44ad-a00f-cac18c1775bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;p0BQe-close&quot;)/i[@class=&quot;z-icon-times&quot;]</value>
      <webElementGuid>5c7e5939-9a0b-4550-b422-2b4e0d7a4ca0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='p0BQe-close']/i</value>
      <webElementGuid>d2952b64-61ad-4a86-96d1-87d9a11c6cee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i</value>
      <webElementGuid>fae84df7-f2aa-47d9-b4c6-b513307635bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
