<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Lokasi Service</name>
   <tag></tag>
   <elementGuidId>b91c4d78-dd85-4ea1-aca9-fd62ea21828b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Lokasi Service' or . = 'Lokasi Service')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#p0BQ9</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Lokasi Service&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a1de6f05-b8da-4bfd-ac01-8299c4dbe82f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>p0BQ9</value>
      <webElementGuid>62234836-5653-47a1-9f20-0bb22ba86e77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>servicelocationlbl z-label</value>
      <webElementGuid>e4599230-4508-45a5-a809-ee3485645bb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lokasi Service</value>
      <webElementGuid>69130130-9049-4868-8cc5-023783ec5caf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;p0BQ9&quot;)</value>
      <webElementGuid>7f7858e6-23d1-464d-a1e6-6bb718c23eb8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='p0BQ9']</value>
      <webElementGuid>042d1912-7684-4fdf-804a-990bd92cd78a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='p0BQ8']/span</value>
      <webElementGuid>8f79b39a-5cff-4ded-be47-b92ce1e9b39f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirm'])[1]/preceding::span[1]</value>
      <webElementGuid>57d580ee-405e-4199-b6e6-a2fd8df42cd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Lokasi Service']/parent::*</value>
      <webElementGuid>1036deda-9f28-42fe-a749-5af17e97ea7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>a4bbef30-ec06-4d23-bcc4-5e2cecdcc7ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'p0BQ9' and (text() = 'Lokasi Service' or . = 'Lokasi Service')]</value>
      <webElementGuid>d9b5ca95-7f83-4af8-a12b-1a9077737a34</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
