<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Error. Password Not Valid</name>
   <tag></tag>
   <elementGuidId>8f6b80a9-5987-4e8e-bc6a-0e3b939709b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#uFHP7</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='uFHP7']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Error!... Password Not Valid&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>97e71aa3-dfc3-4e02-9984-a8c1e452ed71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uFHP7</value>
      <webElementGuid>d301da04-da6e-463a-b66d-a23b5c204c16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Error!... Password Not Valid</value>
      <webElementGuid>422ba5b9-4061-474e-9360-7a36366b048f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uFHP7&quot;)</value>
      <webElementGuid>9b40dbfa-2696-4e66-95c9-89f326f58d96</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='uFHP7']</value>
      <webElementGuid>5d601387-0a7b-4c66-87d1-567e592f8239</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//strong[@id='uFHP6']/span</value>
      <webElementGuid>34802bad-dd70-4225-af4a-1fafad94ef4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='x'])[1]/following::span[1]</value>
      <webElementGuid>5d1d12e3-775d-42cd-88ef-c5a070023d9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign in - DDMS'])[1]/preceding::span[1]</value>
      <webElementGuid>26695a19-faef-43d0-9077-0bd1d7923574</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign in'])[1]/preceding::span[3]</value>
      <webElementGuid>80d24ada-a877-45e5-8951-3ab34ffc9492</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Error!... Password Not Valid']/parent::*</value>
      <webElementGuid>82ab1bae-9ecd-43cc-97b0-14b1cffcc4da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//strong/span</value>
      <webElementGuid>06ed1f9f-4659-49c0-a4be-8090fa6a641e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'uFHP7' and (text() = 'Error!... Password Not Valid' or . = 'Error!... Password Not Valid')]</value>
      <webElementGuid>fba23aa2-9e18-46bf-aa45-ce1a1b8f8c6c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
