<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Error. User Name Not Valid</name>
   <tag></tag>
   <elementGuidId>e1dfc9a0-ef86-4fcb-ad38-a6f12fb863d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#vEGP7</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='vEGP7']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Error!... User Name Not Valid&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>49e91ad9-aaf9-449f-a3dc-4c76f06566d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vEGP7</value>
      <webElementGuid>5ab5b91c-7245-41bb-9a7b-ae98f57b9386</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Error!... User Name Not Valid</value>
      <webElementGuid>11fde72b-d645-4bac-a137-7c1476b5927a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vEGP7&quot;)</value>
      <webElementGuid>50380482-0b12-446a-862f-72a391502be9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='vEGP7']</value>
      <webElementGuid>2e6d4ef3-aeca-4c53-8b01-21079ee00bf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//strong[@id='vEGP6']/span</value>
      <webElementGuid>5de68465-bf47-4681-8dab-0fb0b184ca85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='x'])[1]/following::span[1]</value>
      <webElementGuid>c1b55d5c-ecbd-4ef2-aa79-204040fff4f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign in - DDMS'])[1]/preceding::span[1]</value>
      <webElementGuid>921c01c2-50e3-4ac8-a3b9-f2cdef07da02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign in'])[1]/preceding::span[3]</value>
      <webElementGuid>69560af4-31d8-4aa8-b59e-3d910c39a9b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Error!... User Name Not Valid']/parent::*</value>
      <webElementGuid>857d4816-cc51-4a4e-992a-ac001c819449</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//strong/span</value>
      <webElementGuid>026605a2-e127-4240-9899-5697cf13eabe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'vEGP7' and (text() = 'Error!... User Name Not Valid' or . = 'Error!... User Name Not Valid')]</value>
      <webElementGuid>07889a58-9599-4606-b525-f405554c8bdb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
