<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Pilih Lokasi Service</name>
   <tag></tag>
   <elementGuidId>041aa17e-4d2b-4a92-89c7-bf2ec819d212</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#h7JQa</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/select[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=combobox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>4dfa73c6-d6aa-46d2-a484-979245587afc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>h7JQa</value>
      <webElementGuid>e4af33dd-cf65-4db0-aa25-c092d940f589</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control servicelocation z-select</value>
      <webElementGuid>af353e7b-98ff-4a6d-9d09-8dc83bf9d21f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>selectedindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>cb84bd23-17e2-49ed-a7b5-16fcfd41eeca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih Lokasi ServiceAhass IndukPOS TIGA YOKSPOS UNDERYOKS SATUPOS UNDERYOKS DUA</value>
      <webElementGuid>a683aa97-638a-42c7-bc4e-8b380935a225</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;h7JQa&quot;)</value>
      <webElementGuid>e24d505b-e5d6-46b0-9b3f-ec59539c7c3d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='h7JQa']</value>
      <webElementGuid>d0878678-2c37-45e4-89c5-064a4067eba2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='h7JQ7']/select</value>
      <webElementGuid>8f414c8f-a651-4a41-9251-e18fa2c9df02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lokasi Service'])[1]/following::select[1]</value>
      <webElementGuid>956149da-8718-4ccc-9b57-58040348e125</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirm'])[1]/preceding::select[1]</value>
      <webElementGuid>70f0609b-69f3-42db-9af0-e5713e9460d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>71be7852-58c0-4879-8091-9a3024832c67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'h7JQa' and (text() = 'Pilih Lokasi ServiceAhass IndukPOS TIGA YOKSPOS UNDERYOKS SATUPOS UNDERYOKS DUA' or . = 'Pilih Lokasi ServiceAhass IndukPOS TIGA YOKSPOS UNDERYOKS SATUPOS UNDERYOKS DUA')]</value>
      <webElementGuid>7cd30e6b-15d8-499a-a72a-d55c19c45817</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
