<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link_Hold WO Monitoring</name>
   <tag></tag>
   <elementGuidId>629f96a0-1e7a-40c8-9ccb-f0b8cb58b4a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='bE5Qlb']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#bE5Qlb</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot; Hold WO Monitoring&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>fa580190-504d-4ce0-9f9e-4ea1048ae3df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bE5Qlb</value>
      <webElementGuid>c1b8b80a-89a2-46bd-bdf1-02c692e05f14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-label</value>
      <webElementGuid>8d6c6ab0-a51a-4db2-ad35-787f0c9d4651</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hold WO Monitoring</value>
      <webElementGuid>cd991fff-a1e5-4a2d-8202-9146fb46b48d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bE5Qlb&quot;)</value>
      <webElementGuid>25298d89-3757-4f67-ae57-93925e78f62a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='bE5Qlb']</value>
      <webElementGuid>7d595913-5c71-4597-82d9-e726119ec234</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='bE5Qkb']/span</value>
      <webElementGuid>31b9d3ea-e878-445a-b194-e64018a66845</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Assignment Service'])[1]/following::span[2]</value>
      <webElementGuid>8b1d892d-5824-4bd0-a2d8-20f2d1028810</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='List WO'])[1]/following::span[4]</value>
      <webElementGuid>e0f4f3d1-a9b2-4f81-a0e1-4ddbddee9966</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Final Check'])[1]/preceding::span[1]</value>
      <webElementGuid>73037a0c-3395-4972-a0ce-35aaeaffd0fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pembayaran'])[1]/preceding::span[3]</value>
      <webElementGuid>faaa6b7f-3458-4f13-a7f4-ea406a2b771d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Hold WO Monitoring']/parent::*</value>
      <webElementGuid>0cc7e86e-f748-4f05-8f2a-5d571833456d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/ul/li[4]/a/span/span</value>
      <webElementGuid>970cbfba-3a1e-41fb-8a9d-be6b3ef24221</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'bE5Qlb' and (text() = 'Hold WO Monitoring' or . = 'Hold WO Monitoring')]</value>
      <webElementGuid>6f733c71-f1a6-405c-9ab7-1028a8e3e7a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
