<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link_Assignment Service</name>
   <tag></tag>
   <elementGuidId>93b61d79-35d4-49d1-8b1f-58e656c6addc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='bE5Qdb']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#bE5Qdb</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot; Assignment Service&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5f78a1ac-4885-4fcd-94b4-4c3489a1113e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bE5Qdb</value>
      <webElementGuid>901173ee-6377-403b-8d09-5eb118ae9efc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-label</value>
      <webElementGuid>4bd84876-51a6-401d-a199-170b027c9723</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Assignment Service</value>
      <webElementGuid>95db469c-bb98-4ba2-a7a6-50a2d5cce8b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bE5Qdb&quot;)</value>
      <webElementGuid>f6d09d5d-4b2b-4a25-86dc-3c3a3b624552</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='bE5Qdb']</value>
      <webElementGuid>a7b8ce39-1c62-4172-84b3-e9cb6a14644c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='bE5Qcb']/span</value>
      <webElementGuid>e1fb1a28-1c74-4156-b55c-fc40cebfa0ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='List WO'])[1]/following::span[2]</value>
      <webElementGuid>18dd01ed-9bfc-461a-af28-f5942ce54fe8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Work Order'])[2]/following::span[4]</value>
      <webElementGuid>2edb403a-b3b7-44a5-9e2d-96db20bb78ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hold WO Monitoring'])[1]/preceding::span[1]</value>
      <webElementGuid>dab2a142-6fd2-47c3-9b9f-3322f95ee00f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Final Check'])[1]/preceding::span[3]</value>
      <webElementGuid>65b7e96a-97a4-47f5-82aa-612d1e7d0b4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Assignment Service']/parent::*</value>
      <webElementGuid>1dd8f91c-3d1e-4ca8-86f1-7f27be6f49ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/ul/li[3]/a/span/span</value>
      <webElementGuid>ca7196dd-78f7-47ff-847e-898f73223065</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'bE5Qdb' and (text() = 'Assignment Service' or . = 'Assignment Service')]</value>
      <webElementGuid>e8cb874e-3fcb-4e07-ab86-3a375550a648</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
