<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ddl_Booking Service</name>
   <tag></tag>
   <elementGuidId>cce36a69-978a-4607-9430-4dc20b1edf4e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#g57P1a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='g57P1a']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot; Booking Service &quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6d505734-786e-42d7-937e-17b045e05920</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>g57P1a</value>
      <webElementGuid>2a41ba7b-f8c0-4196-9e35-3eb62cb2b89c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-a</value>
      <webElementGuid>574950cb-33e3-43cb-a22c-7853be4babfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>db1061b8-03ea-48e0-b2b8-ce13d589ce55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Booking Service</value>
      <webElementGuid>365b0f98-dae4-4f5b-bdc6-158719f6f16e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;g57P1a&quot;)</value>
      <webElementGuid>bc0e331b-2263-452d-bf54-3389677479c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='g57P1a']</value>
      <webElementGuid>f18086d4-1ddf-4c23-a803-0bc05607550b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='booking_service_menu']/a</value>
      <webElementGuid>62d0e5e0-1a29-43fe-9b9e-2fbbb7d820d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Monitoring Report'])[1]/following::a[1]</value>
      <webElementGuid>3000a89b-7050-4b42-bef5-1fa43bdab7b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Monitoring Dashboard'])[1]/following::a[2]</value>
      <webElementGuid>c78eecf0-b83d-438e-bb24-185bfeb3dbd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Monitoring Booking Service'])[1]/preceding::a[1]</value>
      <webElementGuid>717ae342-73a6-4e00-adfa-937934baa688</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[42]</value>
      <webElementGuid>3c8ac8bd-c8f4-4a7b-9737-fec9762011d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/a</value>
      <webElementGuid>dbacde2d-6c1a-4aa3-bf70-49e30a32194e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'g57P1a' and @href = '#' and (text() = 'Booking Service' or . = 'Booking Service')]</value>
      <webElementGuid>36a0293d-3ef0-42a1-bc4e-61ae31ed50e3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
