<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ddl_Work Order</name>
   <tag></tag>
   <elementGuidId>597cf39c-e4b6-467e-ad18-4d5871b57a8d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//body[1]/div[2]/div[1]/div[3]/aside[1]/section[1]/ul[1]/li[7]/a[1][count(. | //*[(text() = 'Work Order' or . = 'Work Order')]) = count(//*[(text() = 'Work Order' or . = 'Work Order')])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[1]/div[2]/div[1]/div[3]/aside[1]/section[1]/ul[1]/li[7]/a[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#bE5Qva</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot; Work Order&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>71982229-78d5-4ba8-b625-81ecdf9a2e4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bE5Qva</value>
      <webElementGuid>06f303ca-9721-4b0c-8e5f-4006aa9b77f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-a</value>
      <webElementGuid>33d42824-2473-4e29-8e1b-7ec57cdc7b5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>5895b3b6-d68e-42ef-9588-659008880333</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Work Order</value>
      <webElementGuid>3dc53005-62a9-4543-acc6-25b2446fa705</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//body[1]/div[2]/div[1]/div[3]/aside[1]/section[1]/ul[1]/li[7]/a[1]</value>
      <webElementGuid>56864ef6-b9a7-4879-9e05-2524d11ebbe7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='bE5Qva']</value>
      <webElementGuid>7aaaa2b4-21c2-4487-88e2-e78dc724357b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='wo_wo_menu']/a</value>
      <webElementGuid>0b872294-7daf-46af-8218-0b07bdf6bb28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Work Order'])[1]/following::a[1]</value>
      <webElementGuid>7547bd44-cec3-4e93-8548-4603d52731d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Monitoring Booking Service'])[1]/following::a[2]</value>
      <webElementGuid>ec817b44-7c79-48a5-94e3-1412ae027ea1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='List WO'])[1]/preceding::a[1]</value>
      <webElementGuid>1b2cd66b-0f24-43eb-99c6-163752b3f927</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[45]</value>
      <webElementGuid>0eca8700-ae8c-466b-8806-ad6e0a20d8a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/ul/li/a</value>
      <webElementGuid>b605de86-0fdb-494c-a51f-f888c9377c3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'bE5Qva' and @href = '#' and (text() = 'Work Order' or . = 'Work Order')]</value>
      <webElementGuid>df7029cc-68f2-4884-b88c-5ffed8ff9116</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
