<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_DDMS</name>
   <tag></tag>
   <elementGuidId>6867f6aa-bbcb-4248-8ac3-87e6edf6865f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'DDMS' or . = 'DDMS')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#o1CQ9</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='o1CQ9']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;DDMS&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>fcd23070-879a-4869-bfac-b00f7b8787bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>o1CQ9</value>
      <webElementGuid>5b627786-5f0b-48a6-8f32-47e3aa090d91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-label</value>
      <webElementGuid>f5f082be-d087-480d-914f-4c4ca669fb24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DDMS</value>
      <webElementGuid>5a890088-d935-4384-820c-90e0ac0dcd18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;o1CQ9&quot;)</value>
      <webElementGuid>a3b3eb5d-e224-4e33-8a69-ee34fc2352ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='o1CQ9']</value>
      <webElementGuid>346bbba2-21ff-413b-9ace-d0d9f51cb9b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='o1CQ7']/span</value>
      <webElementGuid>c45b2740-b433-448f-8ccc-0ac3972fffce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NAMA OWNER UNDER YOKS'])[1]/preceding::span[1]</value>
      <webElementGuid>ced212b9-6a97-4570-8b88-5bfb5d4a5245</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout'])[1]/preceding::span[2]</value>
      <webElementGuid>1658b763-199d-4e9f-a7eb-2c65146d48c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='DDMS']/parent::*</value>
      <webElementGuid>1510e428-05ab-4cd2-9299-18aea40e042a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>2634c5e0-87b6-448b-b38f-4d3d8ca5764f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'o1CQ9' and (text() = 'DDMS' or . = 'DDMS')]</value>
      <webElementGuid>aa8a8176-5bda-4251-8711-bbc36dc30c7c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
