<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link_Final Check</name>
   <tag></tag>
   <elementGuidId>0f0bd886-15ef-4871-a1cf-03c649a9930c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[1]/div[2]/div[1]/div[3]/aside[1]/section[1]/ul[1]/li[7]/ul[1]/li[5]/a[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#jLYUtb</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot; Final Check&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>78621add-14c6-4668-bdc6-529d6bd10251</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jLYUtb</value>
      <webElementGuid>ad2575ea-4e1b-4cf7-b2ee-30e8ee3f18ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-label</value>
      <webElementGuid>78857392-f483-4e5c-9452-64b8708ad492</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Final Check</value>
      <webElementGuid>228b5a69-8d72-4809-88c2-afe66e308acc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jLYUtb&quot;)</value>
      <webElementGuid>dc678d58-d42f-406f-91ec-c6a62b18e5f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='jLYUtb']</value>
      <webElementGuid>515afdba-f933-4c13-b312-b1c407f3c8a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='jLYUsb']/span</value>
      <webElementGuid>ab9ea6d3-3168-49a8-8496-7330d3a27370</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hold WO Monitoring'])[1]/following::span[2]</value>
      <webElementGuid>8a362ae3-df8b-4249-b30b-7a5b75da4690</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Assignment Service'])[1]/following::span[4]</value>
      <webElementGuid>21162b36-fdad-4552-9874-40ffcf24c2fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pembayaran'])[1]/preceding::span[1]</value>
      <webElementGuid>3a5e25ae-eae6-4b74-acae-efe6fc3e95d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pembayaran'])[2]/preceding::span[3]</value>
      <webElementGuid>be994f28-a9ee-4543-879d-041cf2c39611</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Final Check']/parent::*</value>
      <webElementGuid>ecf3c48c-1852-4774-9425-54693ccea517</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/ul/li[5]/a/span/span</value>
      <webElementGuid>8884e252-2626-4607-990a-25723083dcb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'jLYUtb' and (text() = 'Final Check' or . = 'Final Check')]</value>
      <webElementGuid>f5d2c111-3db8-4324-ab59-1edcafde8d66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='bE5Qtb']</value>
      <webElementGuid>c856ac49-b8cc-4b75-91d8-2186020afb24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='bE5Qsb']/span</value>
      <webElementGuid>15d9ad85-2d7b-4f8b-9375-dd2f0894fade</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'bE5Qtb' and (text() = 'Final Check' or . = 'Final Check')]</value>
      <webElementGuid>e52460e3-a73f-445e-b353-cb1ef1a281cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
