<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link_Master Unit Customer</name>
   <tag></tag>
   <elementGuidId>e77ab722-1202-482b-be5d-396163c3f07d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[1]/div[2]/div[1]/div[3]/aside[1]/section[1]/ul[1]/li[2]/ul[1]/li[5]/a[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#f8TU13</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot; Master Unit Customer&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>145ccd4c-ac56-4637-b0bd-bd8d6f4306bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>f8TU13</value>
      <webElementGuid>50dd40e6-19d3-46ee-883e-bddf4fa1f8f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-label</value>
      <webElementGuid>75ac02b1-3507-4b28-9ab2-e105f1988b24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Master Unit Customer</value>
      <webElementGuid>468eba1e-af0e-43e2-934b-1750664505ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;f8TU13&quot;)</value>
      <webElementGuid>054e805a-1a62-41cf-87b5-72b066ff8cab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='f8TU13']</value>
      <webElementGuid>07e83962-be06-4169-b950-a2fd02b8940e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='f8TU03']/span</value>
      <webElementGuid>9cb2d94f-1d6b-47ce-b38e-52ae88b7d00b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Master Promo'])[1]/following::span[2]</value>
      <webElementGuid>0e750071-d689-4457-8d8d-b9e09cb412ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Master Market Treatment'])[1]/following::span[4]</value>
      <webElementGuid>af2fb6e1-074a-43a6-882c-962688f92fcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Master Customer Pembawa'])[1]/preceding::span[1]</value>
      <webElementGuid>b5fdd9ac-5291-4d19-bcb9-e009a3e39481</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Master Ahass'])[1]/preceding::span[3]</value>
      <webElementGuid>64b21cec-e219-48a1-8cb4-406380966aa1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Master Unit Customer']/parent::*</value>
      <webElementGuid>3161b8f1-2a2b-46ec-a386-2f64cbe3a892</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/ul/li[5]/a/span/span</value>
      <webElementGuid>b824d51d-a75f-4460-91f0-676aaff6607c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'f8TU13' and (text() = 'Master Unit Customer' or . = 'Master Unit Customer')]</value>
      <webElementGuid>a6d18d76-9a30-429f-8e7c-04db459689aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
