<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link_Assignment Service</name>
   <tag></tag>
   <elementGuidId>93b61d79-35d4-49d1-8b1f-58e656c6addc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[1]/div[2]/div[1]/div[3]/aside[1]/section[1]/ul[1]/li[7]/ul[1]/li[3]/a[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#jLYUdb</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot; Assignment Service&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>52b5f243-837a-44e1-a827-7bb25635bc12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jLYUdb</value>
      <webElementGuid>0e861fe7-8898-4cd6-b33c-0f9bbdff6034</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-label</value>
      <webElementGuid>798c2181-9c9c-4082-a9c3-a0a2d7bc66c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Assignment Service</value>
      <webElementGuid>47e9514a-85cf-46b4-b3e5-ccba60a21ff2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jLYUdb&quot;)</value>
      <webElementGuid>e6e59e9a-245d-4c8c-a6be-0eb5c9bb93dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='jLYUdb']</value>
      <webElementGuid>6b84533b-f67d-405b-a1fe-bbc073efa93c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='jLYUcb']/span</value>
      <webElementGuid>246858ef-c403-4299-85cf-2d1f27bb2c2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='List WO'])[1]/following::span[2]</value>
      <webElementGuid>bede1a77-1f2e-43d3-bd0b-25e90022c303</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Work Order'])[2]/following::span[4]</value>
      <webElementGuid>d11aee17-a332-49e1-9557-6d9bededaf6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hold WO Monitoring'])[1]/preceding::span[1]</value>
      <webElementGuid>11b87756-a95c-48fc-8607-38d46398d088</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Final Check'])[1]/preceding::span[3]</value>
      <webElementGuid>2af42109-c3bd-420f-bf94-427992cbbd91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Assignment Service']/parent::*</value>
      <webElementGuid>32c5659e-0a1a-40a2-b023-de8c38de44bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/ul/li[3]/a/span/span</value>
      <webElementGuid>72154ae9-3ed9-4b6a-8b4c-046e20b6e930</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'jLYUdb' and (text() = 'Assignment Service' or . = 'Assignment Service')]</value>
      <webElementGuid>520c21a6-960f-436d-a7e8-4f6777184623</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='bE5Qdb']</value>
      <webElementGuid>9f47e54a-caf8-495c-963d-60fdd273f2db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='bE5Qcb']/span</value>
      <webElementGuid>a01330e6-986c-4481-9e28-e64276028489</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'bE5Qdb' and (text() = 'Assignment Service' or . = 'Assignment Service')]</value>
      <webElementGuid>a3f6e9a3-47ab-435d-af4d-b6d97b656dad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
