<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link_Monitoring Pembayaran H3</name>
   <tag></tag>
   <elementGuidId>23a5c215-94c7-4c43-8f0e-c5892c3edfff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#jLYUsc</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[1]/div[2]/div[1]/div[3]/aside[1]/section[1]/ul[1]/li[8]/ul[1]/li[3]/a[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot; Monitoring Pembayaran H3&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>817d9f14-0ed2-49ec-b553-5b28535cd669</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jLYUsc</value>
      <webElementGuid>e4690cdd-e27a-4dbd-8679-8aa51fce0b2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-label</value>
      <webElementGuid>ea058df6-8e91-4ad9-b565-28e45aa2f221</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Monitoring Pembayaran H3</value>
      <webElementGuid>17c56e39-eb9e-42e8-b918-8ace3ec6ce29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jLYUsc&quot;)</value>
      <webElementGuid>21ed1364-c687-4206-b7e8-1a13f3c7622f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='jLYUsc']</value>
      <webElementGuid>46a4874a-6590-49d2-9f15-455515075f8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='jLYUrc']/span</value>
      <webElementGuid>1af8a917-e7cc-4be2-a58e-8661f29302f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pembayaran H3'])[1]/following::span[2]</value>
      <webElementGuid>f63ead9b-7ffc-46a3-b18d-287e44db4362</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pembayaran'])[2]/following::span[4]</value>
      <webElementGuid>146cb89c-4a7d-46c4-828e-97bf0b9a31ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Claim C2'])[1]/preceding::span[1]</value>
      <webElementGuid>7cb87dc3-b8d4-4ff8-9efe-327707be1451</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Monitoring Claim C2'])[1]/preceding::span[3]</value>
      <webElementGuid>0e631051-6cba-45cb-9925-fe9552760f51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Monitoring Pembayaran H3']/parent::*</value>
      <webElementGuid>cf1b3bc9-37d7-4914-8f88-d87fcb66d0a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[8]/ul/li[3]/a/span/span</value>
      <webElementGuid>b4f49a29-a5ce-4a6f-a1a7-a071773ab62a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'jLYUsc' and (text() = 'Monitoring Pembayaran H3' or . = 'Monitoring Pembayaran H3')]</value>
      <webElementGuid>6230a586-ff9a-438d-8f93-5848a8a3c219</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
