<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Return</name>
   <tag></tag>
   <elementGuidId>eedfff33-af78-4fca-86bf-37fcddea0d65</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#bBDPnl</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='bBDPnl']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Return&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>db934d5e-38df-4266-a966-d017d3fa4bc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bBDPnl</value>
      <webElementGuid>9e80e4e4-4b27-4e5a-be47-be7c50e3016d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-a</value>
      <webElementGuid>7ed8df3d-c371-4ad9-b1ea-f94819907201</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:;</value>
      <webElementGuid>61b7619d-5083-4b0d-be7e-a6dd2d553b94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                Return
                                            </value>
      <webElementGuid>7b5b6379-c9ff-4b77-a462-42e8480314cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bBDPnl&quot;)</value>
      <webElementGuid>aa4d7f9a-a6a0-4ee1-aee7-07a5c15f6d86</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='bBDPnl']</value>
      <webElementGuid>fb27c3cd-4839-40fa-8fe9-db588c6c8495</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bBDPkl']/a</value>
      <webElementGuid>b91d3755-a53c-41a2-8c83-df4ef19582aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Return')]</value>
      <webElementGuid>5352df6b-8f6b-46bd-a1f6-67363204b93d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Finish'])[1]/following::a[1]</value>
      <webElementGuid>5f1d8bef-80da-48c1-8f79-0246c933efa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BACHTIAR YORK'])[1]/following::a[2]</value>
      <webElementGuid>966db316-60dc-4fd1-9cb6-2ca97d3e2bb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='no data found'])[1]/preceding::a[1]</value>
      <webElementGuid>ca445189-547f-414f-9be9-ba9f92006e29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='/ 1'])[1]/preceding::a[3]</value>
      <webElementGuid>ea818a58-c83e-4bce-9d07-884f7b2d35be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Return']/parent::*</value>
      <webElementGuid>9349a1d2-f6db-4780-8302-d25be3785f66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:;')])[3]</value>
      <webElementGuid>c6beba02-b7a0-43a1-a3ca-cd42d5c8318d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a</value>
      <webElementGuid>5de5d686-e227-4565-ab29-7ba3eb97e38b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'bBDPnl' and @href = 'javascript:;' and (text() = '
                                                Return
                                            ' or . = '
                                                Return
                                            ')]</value>
      <webElementGuid>41fba982-0156-4c78-81c7-b2a8a0e40218</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
