<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Cari No Polisi</name>
   <tag></tag>
   <elementGuidId>77a3c105-c7c7-465b-a580-a73c134e26aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#bBDPgk</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='bBDPgk']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Cari No Polisi&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4c1f05d3-c1bd-4e60-8bbf-3a6c142ab695</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bBDPgk</value>
      <webElementGuid>860aa837-67ef-4634-ab96-1875654bdc36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>9b4d71f3-0852-4384-8fed-cee233d4e7eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>25e3583f-d649-41d6-8e7d-6ff0c7df342c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Cari No Polisi</value>
      <webElementGuid>cd8bbc52-4c40-4c95-9c91-1ae15f8db2ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bBDPgk&quot;)</value>
      <webElementGuid>839644ae-6f1e-4b73-84ba-0dbd1f5752dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='bBDPgk']</value>
      <webElementGuid>8fdcf5ec-39fd-402c-b20d-3faafa4878fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bBDPgk-chdex']/input</value>
      <webElementGuid>291bb96f-df65-4f90-8519-6666daf9af34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>ecd2eb3c-2380-4ef0-8424-59d055d87a7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'bBDPgk' and @type = 'text' and @placeholder = 'Cari No Polisi']</value>
      <webElementGuid>92880627-b96a-49e6-af53-b72e8760d57a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
